"""Repository mappings between ORM rows and simulation domain models."""

from collections.abc import Sequence
from datetime import UTC, datetime
from decimal import Decimal
from typing import Literal, cast
from uuid import UUID

from sqlalchemy import delete, select
from sqlalchemy.orm import Session, sessionmaker

from tiko.db.models import (
    AccountRecord,
    AgentMessageRecord,
    AgentRunRecord,
    AlertRecord,
    AssetRecord,
    AuditLogRecord,
    CandleRecord,
    DatasetCandleRecord,
    DatasetMetadataRecord,
    DatasetQualityReportRecord,
    DecisionRecord,
    DecisionReviewRecord,
    ExperimentRegistryRecord,
    FeatureSnapshotRecord,
    FillRecord,
    LedgerEntryRecord,
    MarketEventRecord,
    MemoryEntryRecord,
    MetricSnapshotRecord,
    ModelRegistryRecord,
    ObservationSnapshotRecord,
    OrderBookSnapshotRecord,
    OrderRecord,
    PluginRegistryRecord,
    PortfolioSnapshotRecord,
    PositionRecord,
    ProjectRecordRow,
    RawMarketDataRecordRow,
    RealtimeEventRecord,
    ReportRecord,
    RiskReviewRecord,
    SimulationDefinitionRecord,
    SimulationRunRecord,
    UserRecord,
)
from tiko.domain.account import (
    LedgerEntry,
    LedgerEntryType,
    MetricSnapshot,
    PortfolioSnapshot,
    Position,
    SimAccount,
)
from tiko.domain.agent import (
    AgentMessage,
    AgentMessageRole,
    AgentRun,
    AgentRunStatus,
)
from tiko.domain.dataset import (
    DatasetQualityIssue,
    DatasetQualityReport,
    DatasetRecord,
    DatasetSource,
    DatasetStatus,
    RawMarketDataRecord,
)
from tiko.domain.decision import DecisionReview, DecisionStatus, TradeIntent
from tiko.domain.experiment import ExperimentKind, ExperimentRecord, ExperimentStatus
from tiko.domain.market import (
    Asset,
    Candle,
    FeatureSnapshot,
    MarketEvent,
    OrderBookSnapshot,
)
from tiko.domain.memory import MemoryEntry
from tiko.domain.model import ModelRegistryEntry, ModelStatus, ModelType
from tiko.domain.observation import Observation
from tiko.domain.order import Fill, SimOrder
from tiko.domain.plugin import (
    PluginManifest,
    PluginRegistryEntry,
    PluginStatus,
    SandboxResult,
)
from tiko.domain.registry import (
    ProjectRecord,
    SimulationDefinition,
    SimulationDefinitionMode,
    UserProfile,
)
from tiko.domain.reporting import (
    Alert,
    AlertCategory,
    AlertSeverity,
    AlertStatus,
    ReportArtifact,
    ReportType,
)
from tiko.domain.risk import RiskReview
from tiko.domain.security import AuditLogEntry, Role
from tiko.domain.simulation import SimulationRun
from tiko.simulation.state import SimulationStepResult

SimulationRunStatus = Literal["created", "running", "paused", "stopped", "completed"]
SimulationMode = Literal[
    "historical_replay", "live_simulated_clock", "synthetic_market"
]
AccountStatus = Literal["active", "paused", "liquidated", "stopped"]
PositionSide = Literal["long", "short", "flat"]
MarketEventType = Literal[
    "candle_closed",
    "tick",
    "orderbook_snapshot",
    "funding_update",
    "news_event",
    "liquidity_shock",
    "volatility_shock",
    "system_event",
]
MarketType = Literal["spot", "perp", "synthetic"]
DecisionAction = Literal[
    "open_long",
    "open_short",
    "increase_long",
    "increase_short",
    "reduce_long",
    "reduce_short",
    "close_position",
    "hold",
    "rebalance",
]
RiskStatus = Literal["approved", "rejected", "resized", "circuit_blocked"]
MemoryType = Literal["decision", "failure", "regime", "agent", "experiment"]
OrderSide = Literal["buy", "sell"]
OrderType = Literal["market", "limit"]
OrderStatus = Literal[
    "created",
    "submitted",
    "accepted",
    "rejected",
    "open",
    "partially_filled",
    "filled",
    "canceled",
    "expired",
]


class SimulationRepository:
    """Persist and load simulation artifacts through SQLAlchemy sessions."""

    def __init__(self, session_factory: sessionmaker[Session]) -> None:
        """Initialize the repository.

        Args:
            session_factory: SQLAlchemy session factory.
        """

        self._session_factory = session_factory

    def save_run(self, run: SimulationRun) -> None:
        """Persist a simulation run and its nested account state.

        Args:
            run: Simulation run to persist.
        """

        with self._session_factory() as session:
            self._merge_run(session, run)
            session.commit()

    def save_step_result(
        self,
        result: SimulationStepResult,
        realtime_envelopes: Sequence[dict[str, object]] = (),
    ) -> None:
        """Persist all durable artifacts generated by one simulation step.

        Args:
            result: Simulation step output to persist.
            realtime_envelopes: Canonical realtime envelopes produced by the step.
        """

        with self._session_factory() as session:
            self._merge_run(session, result.run)
            self._add_candle(session, result.run.run_id, result.candle)
            self._add_orderbook_snapshot(
                session, result.run.run_id, result.orderbook_snapshot
            )
            self._merge_feature_snapshot(session, result.feature_snapshot)
            self._merge_market_event(session, result.run.run_id, result.event)
            self._merge_observation_snapshot(session, result.observation)
            self._merge_decision(session, result.decision)
            self._merge_agent_run(session, result.agent_run)
            for message in result.agent_messages:
                self._merge_agent_message(session, message)
            self._merge_risk_review(session, result.run.run_id, result.risk_review)
            if result.order is not None:
                self._merge_order(session, result.order)
            if result.fill is not None:
                self._merge_fill(session, result.fill)
            self._replace_positions(session, result.run.run_id, result.positions)
            if result.ledger_entry is not None:
                self._merge_ledger_entry(session, result.ledger_entry)
            if result.funding_ledger_entry is not None:
                self._merge_ledger_entry(session, result.funding_ledger_entry)
            self._merge_portfolio_snapshot(session, result.portfolio_snapshot)
            self._merge_metric_snapshot(session, result.metric_snapshot)
            for envelope in realtime_envelopes:
                self._merge_realtime_event(session, envelope)
            session.commit()

    def save_agent_trace(
        self,
        observation: Observation,
        decision: TradeIntent,
        agent_run: AgentRun,
        agent_messages: Sequence[AgentMessage],
    ) -> None:
        """Persist a worker-generated agent trace.

        Args:
            observation: Source observation snapshot.
            decision: Validated trade intent.
            agent_run: Agent run trace artifact.
            agent_messages: Agent messages for the trace.
        """

        with self._session_factory() as session:
            self._merge_observation_snapshot(session, observation)
            self._merge_decision(session, decision)
            self._merge_agent_run(session, agent_run)
            for message in agent_messages:
                self._merge_agent_message(session, message)
            session.commit()

    def save_decision(self, decision: TradeIntent) -> None:
        """Persist one structured trade intent.

        Args:
            decision: Trade intent to persist.
        """

        with self._session_factory() as session:
            self._merge_decision(session, decision)
            session.commit()

    def get_run(self, run_id: UUID) -> SimulationRun | None:
        """Load one simulation run by ID.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Simulation run or `None`.
        """

        with self._session_factory() as session:
            run_record = session.get(SimulationRunRecord, str(run_id))
            if run_record is None:
                return None
            account_record = self._require_account(session, run_record.account_id)
            return self._to_run(run_record, account_record)

    def list_runs(self) -> list[SimulationRun]:
        """List persisted simulation runs ordered by creation time.

        Returns:
            Persisted simulation runs.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(SimulationRunRecord).order_by(SimulationRunRecord.created_at)
            ).all()
            return [
                self._to_run(record, self._require_account(session, record.account_id))
                for record in records
            ]

    def save_user_profile(self, profile: UserProfile) -> None:
        """Persist a control-plane user profile.

        Args:
            profile: User profile to persist.
        """

        with self._session_factory() as session:
            session.merge(
                UserRecord(
                    user_id=profile.user_id,
                    role=profile.role,
                    display_name=profile.display_name,
                    is_disabled=profile.is_disabled,
                    created_at=profile.created_at,
                )
            )
            session.commit()

    def get_user_profile(self, user_id: str) -> UserProfile | None:
        """Load one control-plane user profile.

        Args:
            user_id: User identifier.

        Returns:
            User profile or `None`.
        """

        with self._session_factory() as session:
            record = session.get(UserRecord, user_id)
            if record is None:
                return None
            return self._to_user_profile(record)

    def list_user_profiles(self) -> list[UserProfile]:
        """List control-plane user profiles.

        Returns:
            User profiles ordered by creation time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(UserRecord).order_by(UserRecord.created_at)
            ).all()
            return [self._to_user_profile(record) for record in records]

    def save_project_record(self, project: ProjectRecord) -> None:
        """Persist a project namespace.

        Args:
            project: Project record to persist.
        """

        with self._session_factory() as session:
            session.merge(
                ProjectRecordRow(
                    project_id=str(project.project_id),
                    name=project.name,
                    owner_user_id=project.owner_user_id,
                    description=project.description,
                    created_at=project.created_at,
                )
            )
            session.commit()

    def get_project_record(self, project_id: UUID) -> ProjectRecord | None:
        """Load one project namespace.

        Args:
            project_id: Project identifier.

        Returns:
            Project record or `None`.
        """

        with self._session_factory() as session:
            record = session.get(ProjectRecordRow, str(project_id))
            if record is None:
                return None
            return self._to_project_record(record)

    def list_project_records(self) -> list[ProjectRecord]:
        """List project namespaces.

        Returns:
            Project records ordered by creation time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(ProjectRecordRow).order_by(ProjectRecordRow.created_at)
            ).all()
            return [self._to_project_record(record) for record in records]

    def save_simulation_definition(self, definition: SimulationDefinition) -> None:
        """Persist reusable simulation configuration metadata.

        Args:
            definition: Simulation definition to persist.
        """

        with self._session_factory() as session:
            session.merge(
                SimulationDefinitionRecord(
                    simulation_id=str(definition.simulation_id),
                    project_id=str(definition.project_id)
                    if definition.project_id is not None
                    else None,
                    name=definition.name,
                    mode=definition.mode,
                    symbols=definition.symbols,
                    config=definition.config,
                    created_at=definition.created_at,
                )
            )
            session.commit()

    def get_simulation_definition(
        self, simulation_id: UUID
    ) -> SimulationDefinition | None:
        """Load one simulation definition.

        Args:
            simulation_id: Simulation definition identifier.

        Returns:
            Simulation definition or `None`.
        """

        with self._session_factory() as session:
            record = session.get(SimulationDefinitionRecord, str(simulation_id))
            if record is None:
                return None
            return self._to_simulation_definition(record)

    def list_simulation_definitions(self) -> list[SimulationDefinition]:
        """List simulation definitions.

        Returns:
            Simulation definitions ordered by creation time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(SimulationDefinitionRecord).order_by(
                    SimulationDefinitionRecord.created_at
                )
            ).all()
            return [self._to_simulation_definition(record) for record in records]

    def save_audit_log_entry(self, entry: AuditLogEntry) -> None:
        """Persist an audit log entry.

        Args:
            entry: Audit log entry to persist.
        """

        with self._session_factory() as session:
            session.merge(
                AuditLogRecord(
                    audit_id=str(entry.audit_id),
                    user_id=entry.user_id,
                    role=entry.role,
                    action=entry.action,
                    resource_type=entry.resource_type,
                    resource_id=entry.resource_id,
                    metadata_=entry.metadata,
                    created_at=entry.created_at,
                )
            )
            session.commit()

    def list_audit_log_entries(self) -> list[AuditLogEntry]:
        """List persisted audit log entries.

        Returns:
            Audit log entries ordered by creation time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(AuditLogRecord).order_by(AuditLogRecord.created_at)
            ).all()
            return [self._to_audit_log_entry(record) for record in records]

    def save_asset(self, asset: Asset) -> None:
        """Persist market instrument metadata.

        Args:
            asset: Asset metadata to persist.
        """

        with self._session_factory() as session:
            self._merge_asset(session, asset)
            session.commit()

    def list_assets(self) -> list[Asset]:
        """List persisted market instruments.

        Returns:
            Asset metadata ordered by symbol.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(AssetRecord).order_by(AssetRecord.symbol)
            ).all()
            return [self._to_asset(record) for record in records]

    def save_dataset(
        self,
        dataset: DatasetRecord,
        candles: tuple[Candle, ...],
        quality_report: DatasetQualityReport,
        raw_records: Sequence[RawMarketDataRecord] | None = None,
    ) -> None:
        """Persist imported dataset metadata, candles, and quality details.

        Args:
            dataset: Dataset metadata to persist.
            candles: Normalized candles owned by the dataset.
            quality_report: Latest dataset validation summary.
            raw_records: Optional raw rows to replace for the dataset.
        """

        with self._session_factory() as session:
            self._merge_dataset(session, dataset)
            self._replace_dataset_candles(session, dataset.dataset_id, candles)
            if raw_records is not None:
                self._replace_raw_market_data_records(
                    session, dataset.dataset_id, raw_records
                )
            self._merge_dataset_quality_report(session, quality_report)
            session.commit()

    def get_dataset(self, dataset_id: UUID) -> DatasetRecord | None:
        """Load one imported dataset by ID.

        Args:
            dataset_id: Dataset identifier.

        Returns:
            Dataset record or `None`.
        """

        with self._session_factory() as session:
            record = session.get(DatasetMetadataRecord, str(dataset_id))
            if record is None:
                return None
            return self._to_dataset(record)

    def list_datasets(self) -> list[DatasetRecord]:
        """List imported datasets ordered by creation time.

        Returns:
            Persisted dataset records.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(DatasetMetadataRecord).order_by(DatasetMetadataRecord.created_at)
            ).all()
            return [self._to_dataset(record) for record in records]

    def get_dataset_quality_report(
        self, dataset_id: UUID
    ) -> DatasetQualityReport | None:
        """Load the latest validation report for one dataset.

        Args:
            dataset_id: Dataset identifier.

        Returns:
            Dataset quality report or `None`.
        """

        with self._session_factory() as session:
            record = session.get(DatasetQualityReportRecord, str(dataset_id))
            if record is None:
                return None
            return self._to_dataset_quality_report(record)

    def list_dataset_candles(
        self, dataset_id: UUID, limit: int | None = None
    ) -> list[Candle]:
        """List imported candles for one dataset.

        Args:
            dataset_id: Dataset identifier.
            limit: Optional maximum candles to return.

        Returns:
            Persisted dataset candles ordered by close time.
        """

        with self._session_factory() as session:
            statement = (
                select(DatasetCandleRecord)
                .where(DatasetCandleRecord.dataset_id == str(dataset_id))
                .order_by(DatasetCandleRecord.close_time)
            )
            if limit is not None:
                statement = statement.limit(limit)
            records = session.scalars(statement).all()
            return [self._to_dataset_candle(record) for record in records]

    def list_raw_market_data_records(
        self, dataset_id: UUID
    ) -> list[RawMarketDataRecord]:
        """List raw market data rows for one dataset.

        Args:
            dataset_id: Dataset identifier.

        Returns:
            Persisted raw rows ordered by row index.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(RawMarketDataRecordRow)
                .where(RawMarketDataRecordRow.dataset_id == str(dataset_id))
                .order_by(RawMarketDataRecordRow.row_index)
            ).all()
            return [self._to_raw_market_data_record(record) for record in records]

    def save_experiment(self, experiment: ExperimentRecord) -> None:
        """Persist a research experiment.

        Args:
            experiment: Experiment metadata and lifecycle state to persist.
        """

        with self._session_factory() as session:
            self._merge_experiment(session, experiment)
            session.commit()

    def get_experiment(self, experiment_id: UUID) -> ExperimentRecord | None:
        """Load one research experiment by ID.

        Args:
            experiment_id: Experiment identifier.

        Returns:
            Experiment record or `None`.
        """

        with self._session_factory() as session:
            record = session.get(ExperimentRegistryRecord, str(experiment_id))
            if record is None:
                return None
            return self._to_experiment(record)

    def list_experiments(self) -> list[ExperimentRecord]:
        """List research experiments ordered by creation time.

        Returns:
            Persisted experiment records.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(ExperimentRegistryRecord).order_by(
                    ExperimentRegistryRecord.created_at
                )
            ).all()
            return [self._to_experiment(record) for record in records]

    def list_candles(self, run_id: UUID) -> list[Candle]:
        """List candles persisted for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Persisted candles in close-time order.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(CandleRecord)
                .where(CandleRecord.run_id == str(run_id))
                .order_by(CandleRecord.close_time)
            ).all()
            return [self._to_candle(record) for record in records]

    def list_orderbook_snapshots(self, run_id: UUID) -> list[OrderBookSnapshot]:
        """List order book snapshots persisted for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Order book snapshots ordered by `as_of`.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(OrderBookSnapshotRecord)
                .where(OrderBookSnapshotRecord.run_id == str(run_id))
                .order_by(OrderBookSnapshotRecord.as_of)
            ).all()
            return [self._to_orderbook_snapshot(record) for record in records]

    def list_feature_snapshots(self, run_id: UUID) -> list[FeatureSnapshot]:
        """List feature snapshots persisted for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Feature snapshots ordered by `as_of`.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(FeatureSnapshotRecord)
                .where(FeatureSnapshotRecord.run_id == str(run_id))
                .order_by(FeatureSnapshotRecord.as_of)
            ).all()
            return [self._to_feature_snapshot(record) for record in records]

    def list_market_events(self, run_id: UUID) -> list[MarketEvent]:
        """List market events persisted for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Persisted market events in simulated-time order.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(MarketEventRecord)
                .where(MarketEventRecord.run_id == str(run_id))
                .order_by(MarketEventRecord.simulated_time)
            ).all()
            return [self._to_market_event(record) for record in records]

    def save_market_event(self, run_id: UUID, event: MarketEvent) -> None:
        """Persist one market event for a simulation run.

        Args:
            run_id: Simulation run identifier.
            event: Market event to persist.
        """

        with self._session_factory() as session:
            self._merge_market_event(session, run_id, event)
            session.commit()

    def save_realtime_events(self, envelopes: Sequence[dict[str, object]]) -> None:
        """Persist canonical realtime event envelopes.

        Args:
            envelopes: Realtime event envelopes.
        """

        with self._session_factory() as session:
            for envelope in envelopes:
                self._merge_realtime_event(session, envelope)
            session.commit()

    def list_realtime_events(self, run_id: UUID) -> list[dict[str, object]]:
        """List persisted realtime event envelopes for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Realtime event envelopes ordered by simulated time, topic, and ID.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(RealtimeEventRecord)
                .where(RealtimeEventRecord.run_id == str(run_id))
                .order_by(
                    RealtimeEventRecord.simulated_time,
                    RealtimeEventRecord.topic,
                    RealtimeEventRecord.event_id,
                )
            ).all()
            return [self._to_realtime_event(record) for record in records]

    def list_observation_snapshots(self, run_id: UUID) -> list[Observation]:
        """List observation snapshots persisted for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Observation snapshots ordered by `as_of`.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(ObservationSnapshotRecord)
                .where(ObservationSnapshotRecord.run_id == str(run_id))
                .order_by(ObservationSnapshotRecord.as_of)
            ).all()
            return [self._to_observation_snapshot(record) for record in records]

    def list_agent_runs(self, run_id: UUID | None = None) -> list[AgentRun]:
        """List persisted agent runs.

        Args:
            run_id: Optional simulation run filter.

        Returns:
            Agent runs ordered by simulated start time.
        """

        with self._session_factory() as session:
            statement = select(AgentRunRecord).order_by(
                AgentRunRecord.started_at_sim_time
            )
            if run_id is not None:
                statement = statement.where(AgentRunRecord.run_id == str(run_id))
            records = session.scalars(statement).all()
            return [self._to_agent_run(record) for record in records]

    def list_agent_messages(self, agent_run_id: UUID) -> list[AgentMessage]:
        """List persisted agent messages for one agent run.

        Args:
            agent_run_id: Agent run identifier.

        Returns:
            Agent messages ordered by simulated time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(AgentMessageRecord)
                .where(AgentMessageRecord.agent_run_id == str(agent_run_id))
                .order_by(AgentMessageRecord.created_at_sim_time)
            ).all()
            return [self._to_agent_message(record) for record in records]

    def list_decisions(self, run_id: UUID | None = None) -> list[TradeIntent]:
        """List persisted trade intents.

        Args:
            run_id: Optional simulation run filter.

        Returns:
            Persisted trade intents.
        """

        with self._session_factory() as session:
            statement = select(DecisionRecord).order_by(
                DecisionRecord.created_at_sim_time
            )
            if run_id is not None:
                statement = statement.where(DecisionRecord.run_id == str(run_id))
            records = session.scalars(statement).all()
            return [self._to_decision(record) for record in records]

    def list_orders(self, run_id: UUID | None = None) -> list[SimOrder]:
        """List persisted simulated orders.

        Args:
            run_id: Optional simulation run filter.

        Returns:
            Persisted simulated orders.
        """

        with self._session_factory() as session:
            statement = select(OrderRecord).order_by(OrderRecord.submitted_at_sim_time)
            if run_id is not None:
                statement = statement.where(OrderRecord.run_id == str(run_id))
            records = session.scalars(statement).all()
            return [self._to_order(record) for record in records]

    def list_fills(self, run_id: UUID | None = None) -> list[Fill]:
        """List persisted simulated fills.

        Args:
            run_id: Optional simulation run filter.

        Returns:
            Persisted simulated fills.
        """

        with self._session_factory() as session:
            statement = select(FillRecord).order_by(FillRecord.filled_at_sim_time)
            if run_id is not None:
                statement = statement.where(FillRecord.run_id == str(run_id))
            records = session.scalars(statement).all()
            return [self._to_fill(record) for record in records]

    def list_positions(self, run_id: UUID) -> list[Position]:
        """List persisted current positions for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Persisted current positions.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(PositionRecord)
                .where(PositionRecord.run_id == str(run_id))
                .order_by(PositionRecord.symbol)
            ).all()
            return [self._to_position(record) for record in records]

    def list_ledger_entries(self, run_id: UUID) -> list[LedgerEntry]:
        """List persisted ledger entries for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Ledger entries ordered by simulated time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(LedgerEntryRecord)
                .where(LedgerEntryRecord.run_id == str(run_id))
                .order_by(LedgerEntryRecord.created_at_sim_time)
            ).all()
            return [self._to_ledger_entry(record) for record in records]

    def list_portfolio_snapshots(self, run_id: UUID) -> list[PortfolioSnapshot]:
        """List persisted portfolio snapshots for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Portfolio snapshots ordered by simulated time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(PortfolioSnapshotRecord)
                .where(PortfolioSnapshotRecord.run_id == str(run_id))
                .order_by(PortfolioSnapshotRecord.simulated_time)
            ).all()
            return [self._to_portfolio_snapshot(record) for record in records]

    def list_metric_snapshots(self, run_id: UUID) -> list[MetricSnapshot]:
        """List persisted metric snapshots for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Metric snapshots ordered by simulated time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(MetricSnapshotRecord)
                .where(MetricSnapshotRecord.run_id == str(run_id))
                .order_by(MetricSnapshotRecord.simulated_time)
            ).all()
            return [self._to_metric_snapshot(record) for record in records]

    def get_latest_risk_review(self, run_id: UUID) -> RiskReview | None:
        """Load the latest persisted risk review for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Latest risk review or `None`.
        """

        with self._session_factory() as session:
            record = session.scalars(
                select(RiskReviewRecord)
                .where(RiskReviewRecord.run_id == str(run_id))
                .order_by(RiskReviewRecord.created_at_sim_time.desc())
            ).first()
            if record is None:
                return None
            return self._to_risk_review(record)

    def list_risk_reviews(self, run_id: UUID) -> list[RiskReview]:
        """List persisted risk reviews for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Risk reviews ordered by simulated creation time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(RiskReviewRecord)
                .where(RiskReviewRecord.run_id == str(run_id))
                .order_by(RiskReviewRecord.created_at_sim_time)
            ).all()
            return [self._to_risk_review(record) for record in records]

    def save_decision_review(self, review: DecisionReview) -> None:
        """Persist a posterior decision review.

        Args:
            review: Decision review to persist.
        """

        with self._session_factory() as session:
            self._merge_decision_review(session, review)
            session.commit()

    def list_decision_reviews(self, decision_id: UUID) -> list[DecisionReview]:
        """List posterior reviews for a decision.

        Args:
            decision_id: Trade intent identifier.

        Returns:
            Persisted decision reviews ordered by creation time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(DecisionReviewRecord)
                .where(DecisionReviewRecord.decision_id == str(decision_id))
                .order_by(DecisionReviewRecord.created_at_sim_time)
            ).all()
            return [self._to_decision_review(record) for record in records]

    def save_memory_entry(self, entry: MemoryEntry) -> None:
        """Persist an auxiliary memory entry.

        Args:
            entry: Memory entry to persist.
        """

        with self._session_factory() as session:
            self._merge_memory_entry(session, entry)
            session.commit()

    def list_memory_entries(self, run_id: UUID) -> list[MemoryEntry]:
        """List memory entries for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Persisted memory entries ordered by availability.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(MemoryEntryRecord)
                .where(MemoryEntryRecord.run_id == str(run_id))
                .order_by(MemoryEntryRecord.available_at_sim_time)
            ).all()
            return [self._to_memory_entry(record) for record in records]

    def save_model_registry_entry(self, entry: ModelRegistryEntry) -> None:
        """Persist a model registry entry.

        Args:
            entry: Model registry entry to persist.
        """

        with self._session_factory() as session:
            self._merge_model_registry_entry(session, entry)
            session.commit()

    def get_model_registry_entry(self, model_id: UUID) -> ModelRegistryEntry | None:
        """Load one model registry entry.

        Args:
            model_id: Model identifier.

        Returns:
            Model registry entry or `None`.
        """

        with self._session_factory() as session:
            record = session.get(ModelRegistryRecord, str(model_id))
            if record is None:
                return None
            return self._to_model_registry_entry(record)

    def list_model_registry_entries(self) -> list[ModelRegistryEntry]:
        """List model registry entries ordered by creation time.

        Returns:
            Persisted model registry entries.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(ModelRegistryRecord).order_by(ModelRegistryRecord.created_at)
            ).all()
            return [self._to_model_registry_entry(record) for record in records]

    def save_plugin_registry_entry(self, entry: PluginRegistryEntry) -> None:
        """Persist a plugin registry entry.

        Args:
            entry: Plugin registry entry to persist.
        """

        with self._session_factory() as session:
            self._merge_plugin_registry_entry(session, entry)
            session.commit()

    def get_plugin_registry_entry(self, plugin_id: UUID) -> PluginRegistryEntry | None:
        """Load one plugin registry entry.

        Args:
            plugin_id: Plugin identifier.

        Returns:
            Plugin registry entry or `None`.
        """

        with self._session_factory() as session:
            record = session.get(PluginRegistryRecord, str(plugin_id))
            if record is None:
                return None
            return self._to_plugin_registry_entry(record)

    def list_plugin_registry_entries(self) -> list[PluginRegistryEntry]:
        """List plugin registry entries ordered by creation time.

        Returns:
            Persisted plugin registry entries.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(PluginRegistryRecord).order_by(PluginRegistryRecord.created_at)
            ).all()
            return [self._to_plugin_registry_entry(record) for record in records]

    def save_report(self, report: ReportArtifact) -> None:
        """Persist a structured report.

        Args:
            report: Report artifact to persist.
        """

        with self._session_factory() as session:
            self._merge_report(session, report)
            session.commit()

    def get_report(self, report_id: UUID) -> ReportArtifact | None:
        """Load one structured report by ID.

        Args:
            report_id: Report identifier.

        Returns:
            Report artifact or `None`.
        """

        with self._session_factory() as session:
            record = session.get(ReportRecord, str(report_id))
            if record is None:
                return None
            return self._to_report(record)

    def list_reports(self, run_id: UUID) -> list[ReportArtifact]:
        """List reports for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Reports ordered by creation time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(ReportRecord)
                .where(ReportRecord.run_id == str(run_id))
                .order_by(ReportRecord.created_at)
            ).all()
            return [self._to_report(record) for record in records]

    def save_alert(self, alert: Alert) -> None:
        """Persist a run-scoped alert.

        Args:
            alert: Alert to persist.
        """

        with self._session_factory() as session:
            self._merge_alert(session, alert)
            session.commit()

    def list_alerts(self, run_id: UUID) -> list[Alert]:
        """List alerts for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Alerts ordered by creation time.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(AlertRecord)
                .where(AlertRecord.run_id == str(run_id))
                .order_by(AlertRecord.created_at)
            ).all()
            return [self._to_alert(record) for record in records]

    def _merge_run(self, session: Session, run: SimulationRun) -> None:
        """Merge a run and its account into the active session.

        Args:
            session: Active SQLAlchemy session.
            run: Simulation run to merge.
        """

        self._merge_account(session, run.account)
        session.merge(
            SimulationRunRecord(
                run_id=str(run.run_id),
                name=run.name,
                status=run.status,
                mode=run.mode,
                account_id=str(run.account.account_id),
                symbols=run.symbols,
                start_sim_time=run.start_sim_time,
                current_sim_time=run.current_sim_time,
                end_sim_time=run.end_sim_time,
                speed_multiplier=run.speed_multiplier,
                config=run.config,
                created_at=run.created_at,
            )
        )

    def _merge_account(self, session: Session, account: SimAccount) -> None:
        """Merge an account into the active session.

        Args:
            session: Active SQLAlchemy session.
            account: Simulated account to merge.
        """

        session.merge(
            AccountRecord(
                account_id=str(account.account_id),
                name=account.name,
                base_currency=account.base_currency,
                initial_equity=account.initial_equity,
                cash_balance=account.cash_balance,
                total_equity=account.total_equity,
                realized_pnl=account.realized_pnl,
                unrealized_pnl=account.unrealized_pnl,
                max_drawdown=account.max_drawdown,
                status=account.status,
            )
        )

    def _merge_asset(self, session: Session, asset: Asset) -> None:
        """Merge asset metadata into the active session.

        Args:
            session: Active SQLAlchemy session.
            asset: Asset metadata to merge.
        """

        session.merge(
            AssetRecord(
                symbol=asset.symbol,
                base_asset=asset.base_asset,
                quote_asset=asset.quote_asset,
                market_type=asset.market_type,
                tick_size=asset.tick_size,
                lot_size=asset.lot_size,
                min_notional=asset.min_notional,
                fee_tier=asset.fee_tier,
                is_active=asset.is_active,
            )
        )

    def _replace_positions(
        self, session: Session, run_id: UUID, positions: tuple[Position, ...]
    ) -> None:
        """Replace current positions for a simulation run.

        Args:
            session: Active SQLAlchemy session.
            run_id: Simulation run identifier.
            positions: Current net simulated positions.
        """

        session.execute(
            delete(PositionRecord).where(PositionRecord.run_id == str(run_id))
        )
        session.add_all(
            PositionRecord(
                position_id=str(position.position_id),
                run_id=str(run_id),
                account_id=str(position.account_id),
                symbol=position.symbol,
                side=position.side,
                quantity=position.quantity,
                avg_entry_price=position.avg_entry_price,
                mark_price=position.mark_price,
                notional=position.notional,
                leverage=position.leverage,
                unrealized_pnl=position.unrealized_pnl,
                realized_pnl=position.realized_pnl,
                liquidation_price=position.liquidation_price,
                updated_at_sim_time=position.updated_at_sim_time,
            )
            for position in positions
        )

    def _merge_dataset(self, session: Session, dataset: DatasetRecord) -> None:
        """Merge dataset metadata into the active session.

        Args:
            session: Active SQLAlchemy session.
            dataset: Dataset metadata to merge.
        """

        session.merge(
            DatasetMetadataRecord(
                dataset_id=str(dataset.dataset_id),
                name=dataset.name,
                source=dataset.source,
                source_uri=dataset.source_uri,
                symbols=dataset.symbols,
                timeframes=dataset.timeframes,
                candle_count=dataset.candle_count,
                status=dataset.status,
                start_time=dataset.start_time,
                end_time=dataset.end_time,
                created_at=dataset.created_at,
            )
        )

    def _replace_dataset_candles(
        self, session: Session, dataset_id: UUID, candles: tuple[Candle, ...]
    ) -> None:
        """Replace all normalized candles for one dataset.

        Args:
            session: Active SQLAlchemy session.
            dataset_id: Dataset identifier.
            candles: Replacement candle sequence.
        """

        session.execute(
            delete(DatasetCandleRecord).where(
                DatasetCandleRecord.dataset_id == str(dataset_id)
            )
        )
        session.add_all(
            DatasetCandleRecord(
                dataset_id=str(dataset_id),
                symbol=candle.symbol,
                timeframe=candle.timeframe,
                open_time=candle.open_time,
                close_time=candle.close_time,
                open=candle.open,
                high=candle.high,
                low=candle.low,
                close=candle.close,
                volume=candle.volume,
                quote_volume=candle.quote_volume,
                source=candle.source,
                as_of=candle.as_of,
                fetched_at=candle.fetched_at,
                ingestion_run_id=str(candle.ingestion_run_id)
                if candle.ingestion_run_id is not None
                else None,
                created_at=candle.created_at,
            )
            for candle in candles
        )

    def _replace_raw_market_data_records(
        self,
        session: Session,
        dataset_id: UUID,
        raw_records: Sequence[RawMarketDataRecord],
    ) -> None:
        """Replace all raw market data rows for one dataset.

        Args:
            session: Active SQLAlchemy session.
            dataset_id: Dataset identifier.
            raw_records: Replacement raw row sequence.
        """

        session.execute(
            delete(RawMarketDataRecordRow).where(
                RawMarketDataRecordRow.dataset_id == str(dataset_id)
            )
        )
        session.add_all(
            RawMarketDataRecordRow(
                raw_record_id=str(record.raw_record_id),
                dataset_id=str(record.dataset_id),
                ingestion_run_id=str(record.ingestion_run_id),
                source=record.source,
                source_uri=record.source_uri,
                row_index=record.row_index,
                payload=record.payload,
                fetched_at=record.fetched_at,
                created_at=record.created_at,
            )
            for record in raw_records
        )

    def _merge_dataset_quality_report(
        self, session: Session, report: DatasetQualityReport
    ) -> None:
        """Merge a dataset validation report into the active session.

        Args:
            session: Active SQLAlchemy session.
            report: Dataset quality report to merge.
        """

        session.merge(
            DatasetQualityReportRecord(
                dataset_id=str(report.dataset_id),
                total_records=report.total_records,
                error_count=report.error_count,
                warning_count=report.warning_count,
                has_errors=report.has_errors,
                issues=[issue.model_dump(mode="json") for issue in report.issues],
            )
        )

    def _merge_experiment(self, session: Session, experiment: ExperimentRecord) -> None:
        """Merge a research experiment into the active session.

        Args:
            session: Active SQLAlchemy session.
            experiment: Experiment record to merge.
        """

        session.merge(
            ExperimentRegistryRecord(
                experiment_id=str(experiment.experiment_id),
                name=experiment.name,
                kind=experiment.kind,
                hypothesis=experiment.hypothesis,
                dataset_id=str(experiment.dataset_id),
                model_id=str(experiment.model_id)
                if experiment.model_id is not None
                else None,
                parameters=experiment.parameters,
                status=experiment.status,
                metrics=experiment.metrics,
                created_at=experiment.created_at,
                queued_at=experiment.queued_at,
                completed_at=experiment.completed_at,
            )
        )

    def _add_candle(self, session: Session, run_id: UUID, candle: Candle) -> None:
        """Add a candle row for a simulation run.

        Args:
            session: Active SQLAlchemy session.
            run_id: Simulation run identifier.
            candle: Candle to persist.
        """

        session.add(
            CandleRecord(
                run_id=str(run_id),
                symbol=candle.symbol,
                timeframe=candle.timeframe,
                open_time=candle.open_time,
                close_time=candle.close_time,
                open=candle.open,
                high=candle.high,
                low=candle.low,
                close=candle.close,
                volume=candle.volume,
                quote_volume=candle.quote_volume,
                source=candle.source,
                as_of=candle.as_of,
                fetched_at=candle.fetched_at,
                ingestion_run_id=str(candle.ingestion_run_id)
                if candle.ingestion_run_id is not None
                else None,
                created_at=candle.created_at,
            )
        )

    def _add_orderbook_snapshot(
        self, session: Session, run_id: UUID, snapshot: OrderBookSnapshot
    ) -> None:
        """Add an order book snapshot row for a simulation run.

        Args:
            session: Active SQLAlchemy session.
            run_id: Simulation run identifier.
            snapshot: Order book snapshot to persist.
        """

        session.add(
            OrderBookSnapshotRecord(
                run_id=str(run_id),
                symbol=snapshot.symbol,
                as_of=snapshot.as_of,
                bids=[[str(price), str(quantity)] for price, quantity in snapshot.bids],
                asks=[[str(price), str(quantity)] for price, quantity in snapshot.asks],
                mid_price=snapshot.mid_price,
                spread_bps=snapshot.spread_bps,
                depth_1pct_usd=snapshot.depth_1pct_usd,
                source=snapshot.source,
                sequence_number=snapshot.sequence_number,
                checksum=snapshot.checksum,
                expected_checksum=snapshot.expected_checksum,
            )
        )

    def _merge_feature_snapshot(
        self, session: Session, snapshot: FeatureSnapshot
    ) -> None:
        """Merge a feature snapshot into the active session.

        Args:
            session: Active SQLAlchemy session.
            snapshot: Feature snapshot to merge.
        """

        session.merge(
            FeatureSnapshotRecord(
                snapshot_id=str(snapshot.snapshot_id),
                run_id=str(snapshot.run_id),
                symbol=snapshot.symbol,
                as_of=snapshot.as_of,
                features=snapshot.features,
                source=snapshot.source,
            )
        )

    def _merge_market_event(
        self, session: Session, run_id: UUID, event: MarketEvent
    ) -> None:
        """Merge a market event into the active session.

        Args:
            session: Active SQLAlchemy session.
            run_id: Simulation run identifier.
            event: Market event to merge.
        """

        session.merge(
            MarketEventRecord(
                event_id=str(event.event_id),
                run_id=str(run_id),
                type=event.type,
                symbol=event.symbol,
                simulated_time=event.simulated_time,
                payload=event.payload,
                source=event.source,
                confidence=event.confidence,
            )
        )

    def _merge_realtime_event(
        self,
        session: Session,
        envelope: dict[str, object],
    ) -> None:
        """Merge a realtime envelope into the active session.

        Args:
            session: Active SQLAlchemy session.
            envelope: Realtime event envelope to merge.
        """

        session.merge(
            RealtimeEventRecord(
                event_id=self._read_realtime_envelope_string(envelope, "event_id"),
                run_id=self._read_realtime_envelope_string(envelope, "run_id"),
                topic=self._read_realtime_envelope_string(envelope, "topic"),
                simulated_time=self._read_realtime_envelope_time(envelope),
                payload=self._read_realtime_envelope_payload(envelope),
                created_at=datetime.now(UTC),
            )
        )

    def _merge_observation_snapshot(
        self, session: Session, observation: Observation
    ) -> None:
        """Merge an observation snapshot into the active session.

        Args:
            session: Active SQLAlchemy session.
            observation: Observation snapshot to merge.
        """

        session.merge(
            ObservationSnapshotRecord(
                observation_id=str(observation.observation_id),
                run_id=str(observation.run_id),
                symbol=observation.symbol,
                as_of=observation.as_of,
                payload=observation.model_dump(mode="json"),
                created_at=observation.as_of,
            )
        )

    def _merge_agent_run(self, session: Session, agent_run: AgentRun) -> None:
        """Merge an agent run into the active session.

        Args:
            session: Active SQLAlchemy session.
            agent_run: Agent run to merge.
        """

        session.merge(
            AgentRunRecord(
                agent_run_id=str(agent_run.agent_run_id),
                run_id=str(agent_run.run_id),
                decision_id=str(agent_run.decision_id),
                agent_id=agent_run.agent_id,
                status=agent_run.status,
                started_at_sim_time=agent_run.started_at_sim_time,
                completed_at_sim_time=agent_run.completed_at_sim_time,
            )
        )

    def _merge_agent_message(self, session: Session, message: AgentMessage) -> None:
        """Merge an agent message into the active session.

        Args:
            session: Active SQLAlchemy session.
            message: Agent message to merge.
        """

        session.merge(
            AgentMessageRecord(
                message_id=str(message.message_id),
                agent_run_id=str(message.agent_run_id),
                role=message.role,
                content=message.content,
                created_at_sim_time=message.created_at_sim_time,
            )
        )

    def _merge_decision(self, session: Session, decision: TradeIntent) -> None:
        """Merge a trade intent into the active session.

        Args:
            session: Active SQLAlchemy session.
            decision: Trade intent to merge.

        Raises:
            ValueError: If provenance fields required for persistence are missing.
        """

        if decision.observation_id is None:
            raise ValueError("Persisted decisions require observation_id.")
        if decision.agent_run_id is None:
            raise ValueError("Persisted decisions require agent_run_id.")
        if decision.input_data_as_of is None:
            raise ValueError("Persisted decisions require input_data_as_of.")
        session.merge(
            DecisionRecord(
                decision_id=str(decision.decision_id),
                run_id=str(decision.run_id),
                observation_id=str(decision.observation_id),
                agent_run_id=str(decision.agent_run_id),
                input_data_as_of=decision.input_data_as_of,
                agent_id=decision.agent_id,
                symbol=decision.symbol,
                market_type=decision.market_type,
                action=decision.action,
                target_weight=decision.target_weight,
                target_notional=decision.target_notional,
                max_leverage=decision.max_leverage,
                confidence=decision.confidence,
                expected_holding_period=decision.expected_holding_period,
                thesis=decision.thesis,
                evidence=decision.evidence,
                invalidation_conditions=decision.invalidation_conditions,
                data_quality_score=decision.data_quality_score,
                status=decision.status,
                created_at_sim_time=decision.created_at_sim_time,
            )
        )

    def _merge_risk_review(
        self, session: Session, run_id: UUID, review: RiskReview
    ) -> None:
        """Merge a risk review into the active session.

        Args:
            session: Active SQLAlchemy session.
            run_id: Simulation run identifier.
            review: Risk review to merge.
        """

        session.merge(
            RiskReviewRecord(
                review_id=str(review.review_id),
                run_id=str(run_id),
                decision_id=str(review.decision_id),
                status=review.status,
                original_target_weight=review.original_target_weight,
                approved_target_weight=review.approved_target_weight,
                max_order_notional=review.max_order_notional,
                reasons=review.reasons,
                triggered_rules=review.triggered_rules,
                created_at_sim_time=review.created_at_sim_time,
            )
        )

    def _merge_decision_review(self, session: Session, review: DecisionReview) -> None:
        """Merge a posterior decision review into the active session.

        Args:
            session: Active SQLAlchemy session.
            review: Decision review to merge.
        """

        session.merge(
            DecisionReviewRecord(
                review_id=str(review.review_id),
                decision_id=str(review.decision_id),
                run_id=str(review.run_id),
                horizon=review.horizon,
                realized_return=review.realized_return,
                max_adverse_excursion=review.max_adverse_excursion,
                max_favorable_excursion=review.max_favorable_excursion,
                was_correct_directionally=review.was_correct_directionally,
                error_tags=review.error_tags,
                reviewer_summary=review.reviewer_summary,
                created_at_sim_time=review.created_at_sim_time,
            )
        )

    def _merge_memory_entry(self, session: Session, entry: MemoryEntry) -> None:
        """Merge an auxiliary memory entry into the active session.

        Args:
            session: Active SQLAlchemy session.
            entry: Memory entry to merge.
        """

        session.merge(
            MemoryEntryRecord(
                memory_id=str(entry.memory_id),
                run_id=str(entry.run_id),
                decision_id=str(entry.decision_id) if entry.decision_id else None,
                memory_type=entry.memory_type,
                summary=entry.summary,
                content=entry.content,
                tags=entry.tags,
                available_at_sim_time=entry.available_at_sim_time,
                created_at=entry.created_at,
            )
        )

    def _merge_model_registry_entry(
        self, session: Session, entry: ModelRegistryEntry
    ) -> None:
        """Merge a model registry entry into the active session.

        Args:
            session: Active SQLAlchemy session.
            entry: Model registry entry to merge.
        """

        session.merge(
            ModelRegistryRecord(
                model_id=str(entry.model_id),
                name=entry.name,
                version=entry.version,
                model_type=entry.model_type,
                algorithm=entry.algorithm,
                training_dataset_id=str(entry.training_dataset_id),
                validation_dataset_id=str(entry.validation_dataset_id),
                metrics=entry.metrics,
                artifact_uri=entry.artifact_uri,
                status=entry.status,
                created_at=entry.created_at,
            )
        )

    def _merge_plugin_registry_entry(
        self, session: Session, entry: PluginRegistryEntry
    ) -> None:
        """Merge a plugin registry entry into the active session.

        Args:
            session: Active SQLAlchemy session.
            entry: Plugin registry entry to merge.
        """

        session.merge(
            PluginRegistryRecord(
                plugin_id=str(entry.plugin_id),
                manifest=entry.manifest.model_dump(mode="json"),
                sandbox_result=entry.sandbox_result.model_dump(mode="json"),
                status=entry.status,
                created_at=entry.created_at,
            )
        )

    def _merge_report(self, session: Session, report: ReportArtifact) -> None:
        """Merge a report artifact into the active session.

        Args:
            session: Active SQLAlchemy session.
            report: Report artifact to merge.
        """

        session.merge(
            ReportRecord(
                report_id=str(report.report_id),
                run_id=str(report.run_id),
                report_type=report.report_type,
                title=report.title,
                summary=report.summary,
                sections=report.sections,
                created_at_sim_time=report.created_at_sim_time,
                created_at=report.created_at,
            )
        )

    def _merge_alert(self, session: Session, alert: Alert) -> None:
        """Merge an alert into the active session.

        Args:
            session: Active SQLAlchemy session.
            alert: Alert to merge.
        """

        session.merge(
            AlertRecord(
                alert_id=str(alert.alert_id),
                run_id=str(alert.run_id),
                category=alert.category,
                severity=alert.severity,
                message=alert.message,
                status=alert.status,
                created_at_sim_time=alert.created_at_sim_time,
                created_at=alert.created_at,
            )
        )

    def _merge_order(self, session: Session, order: SimOrder) -> None:
        """Merge a simulated order into the active session.

        Args:
            session: Active SQLAlchemy session.
            order: Simulated order to merge.
        """

        session.merge(
            OrderRecord(
                order_id=str(order.order_id),
                run_id=str(order.run_id),
                account_id=str(order.account_id),
                decision_id=str(order.decision_id) if order.decision_id else None,
                symbol=order.symbol,
                side=order.side,
                order_type=order.order_type,
                quantity=order.quantity,
                limit_price=order.limit_price,
                status=order.status,
                submitted_at_sim_time=order.submitted_at_sim_time,
                updated_at_sim_time=order.updated_at_sim_time,
            )
        )

    def _merge_fill(self, session: Session, fill: Fill) -> None:
        """Merge a simulated fill into the active session.

        Args:
            session: Active SQLAlchemy session.
            fill: Simulated fill to merge.
        """

        session.merge(
            FillRecord(
                fill_id=str(fill.fill_id),
                order_id=str(fill.order_id),
                run_id=str(fill.run_id),
                symbol=fill.symbol,
                side=fill.side,
                quantity=fill.quantity,
                price=fill.price,
                fee=fill.fee,
                slippage_bps=fill.slippage_bps,
                filled_at_sim_time=fill.filled_at_sim_time,
            )
        )

    def _merge_ledger_entry(self, session: Session, entry: LedgerEntry) -> None:
        """Merge a simulated ledger entry into the active session.

        Args:
            session: Active SQLAlchemy session.
            entry: Ledger entry to merge.
        """

        session.merge(
            LedgerEntryRecord(
                ledger_entry_id=str(entry.ledger_entry_id),
                run_id=str(entry.run_id),
                account_id=str(entry.account_id),
                fill_id=str(entry.fill_id) if entry.fill_id else None,
                entry_type=entry.entry_type,
                symbol=entry.symbol,
                quantity=entry.quantity,
                price=entry.price,
                notional=entry.notional,
                cash_delta=entry.cash_delta,
                fee=entry.fee,
                realized_pnl_delta=entry.realized_pnl_delta,
                created_at_sim_time=entry.created_at_sim_time,
                created_at=entry.created_at,
            )
        )

    def _merge_portfolio_snapshot(
        self, session: Session, snapshot: PortfolioSnapshot
    ) -> None:
        """Merge a portfolio snapshot into the active session.

        Args:
            session: Active SQLAlchemy session.
            snapshot: Portfolio snapshot to merge.
        """

        session.merge(
            PortfolioSnapshotRecord(
                snapshot_id=str(snapshot.snapshot_id),
                run_id=str(snapshot.run_id),
                account_id=str(snapshot.account_id),
                simulated_time=snapshot.simulated_time,
                cash_balance=snapshot.cash_balance,
                total_equity=snapshot.total_equity,
                realized_pnl=snapshot.realized_pnl,
                unrealized_pnl=snapshot.unrealized_pnl,
                max_drawdown=snapshot.max_drawdown,
                gross_exposure=snapshot.gross_exposure,
                net_exposure=snapshot.net_exposure,
                created_at=snapshot.created_at,
            )
        )

    def _merge_metric_snapshot(
        self, session: Session, snapshot: MetricSnapshot
    ) -> None:
        """Merge a metric snapshot into the active session.

        Args:
            session: Active SQLAlchemy session.
            snapshot: Metric snapshot to merge.
        """

        session.merge(
            MetricSnapshotRecord(
                snapshot_id=str(snapshot.snapshot_id),
                run_id=str(snapshot.run_id),
                simulated_time=snapshot.simulated_time,
                metrics=snapshot.metrics,
                created_at=snapshot.created_at,
            )
        )

    def _require_account(self, session: Session, account_id: str) -> AccountRecord:
        """Load an account or fail when persisted run state is inconsistent.

        Args:
            session: Active SQLAlchemy session.
            account_id: Account identifier.

        Returns:
            Persisted account record.

        Raises:
            LookupError: If the account row is missing.
        """

        record = session.get(AccountRecord, account_id)
        if record is None:
            raise LookupError(f"Missing account row {account_id}.")
        return record

    def _to_audit_log_entry(self, record: AuditLogRecord) -> AuditLogEntry:
        """Convert an audit log row to a domain model.

        Args:
            record: Persisted audit log row.

        Returns:
            Audit log domain model.
        """

        return AuditLogEntry(
            audit_id=UUID(record.audit_id),
            user_id=record.user_id,
            role=cast(Role, record.role),
            action=record.action,
            resource_type=record.resource_type,
            resource_id=record.resource_id,
            metadata=dict(record.metadata_),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_user_profile(self, record: UserRecord) -> UserProfile:
        """Convert a user row to a domain model.

        Args:
            record: Persisted user row.

        Returns:
            User profile domain model.
        """

        return UserProfile(
            user_id=record.user_id,
            role=cast(Role, record.role),
            display_name=record.display_name,
            is_disabled=record.is_disabled,
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_project_record(self, record: ProjectRecordRow) -> ProjectRecord:
        """Convert a project row to a domain model.

        Args:
            record: Persisted project row.

        Returns:
            Project record domain model.
        """

        return ProjectRecord(
            project_id=UUID(record.project_id),
            name=record.name,
            owner_user_id=record.owner_user_id,
            description=record.description,
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_simulation_definition(
        self, record: SimulationDefinitionRecord
    ) -> SimulationDefinition:
        """Convert a simulation definition row to a domain model.

        Args:
            record: Persisted simulation definition row.

        Returns:
            Simulation definition domain model.
        """

        return SimulationDefinition(
            simulation_id=UUID(record.simulation_id),
            project_id=UUID(record.project_id) if record.project_id else None,
            name=record.name,
            mode=cast(SimulationDefinitionMode, record.mode),
            symbols=list(record.symbols),
            config=dict(record.config),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_run(
        self, record: SimulationRunRecord, account_record: AccountRecord
    ) -> SimulationRun:
        """Convert a run row and account row to a domain model.

        Args:
            record: Persisted run row.
            account_record: Persisted account row.

        Returns:
            Simulation run domain model.
        """

        return SimulationRun(
            run_id=UUID(record.run_id),
            name=record.name,
            status=cast(SimulationRunStatus, record.status),
            mode=cast(SimulationMode, record.mode),
            account=self._to_account(account_record),
            symbols=list(record.symbols),
            start_sim_time=self._aware_datetime(record.start_sim_time),
            current_sim_time=self._aware_datetime(record.current_sim_time),
            end_sim_time=self._optional_aware_datetime(record.end_sim_time),
            speed_multiplier=record.speed_multiplier,
            config=dict(record.config),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_account(self, record: AccountRecord) -> SimAccount:
        """Convert an account row to a domain model.

        Args:
            record: Persisted account row.

        Returns:
            Simulated account domain model.
        """

        return SimAccount(
            account_id=UUID(record.account_id),
            name=record.name,
            base_currency=record.base_currency,
            initial_equity=record.initial_equity,
            cash_balance=record.cash_balance,
            total_equity=record.total_equity,
            realized_pnl=record.realized_pnl,
            unrealized_pnl=record.unrealized_pnl,
            max_drawdown=record.max_drawdown,
            status=cast(AccountStatus, record.status),
        )

    def _to_asset(self, record: AssetRecord) -> Asset:
        """Convert an asset row to a domain model.

        Args:
            record: Persisted asset row.

        Returns:
            Asset domain model.
        """

        return Asset(
            symbol=record.symbol,
            base_asset=record.base_asset,
            quote_asset=record.quote_asset,
            market_type=cast(MarketType, record.market_type),
            tick_size=record.tick_size,
            lot_size=record.lot_size,
            min_notional=record.min_notional,
            fee_tier=record.fee_tier,
            is_active=record.is_active,
        )

    def _to_position(self, record: PositionRecord) -> Position:
        """Convert a position row to a domain model.

        Args:
            record: Persisted position row.

        Returns:
            Position domain model.
        """

        return Position(
            position_id=UUID(record.position_id),
            account_id=UUID(record.account_id),
            symbol=record.symbol,
            side=cast(PositionSide, record.side),
            quantity=record.quantity,
            avg_entry_price=record.avg_entry_price,
            mark_price=record.mark_price,
            notional=record.notional,
            leverage=record.leverage,
            unrealized_pnl=record.unrealized_pnl,
            realized_pnl=record.realized_pnl,
            liquidation_price=record.liquidation_price,
            updated_at_sim_time=self._aware_datetime(record.updated_at_sim_time),
        )

    def _to_dataset(self, record: DatasetMetadataRecord) -> DatasetRecord:
        """Convert a dataset metadata row to a domain model.

        Args:
            record: Persisted dataset row.

        Returns:
            Dataset domain model.
        """

        return DatasetRecord(
            dataset_id=UUID(record.dataset_id),
            name=record.name,
            source=cast(DatasetSource, record.source),
            source_uri=record.source_uri,
            symbols=list(record.symbols),
            timeframes=list(record.timeframes),
            candle_count=record.candle_count,
            status=cast(DatasetStatus, record.status),
            start_time=self._optional_aware_datetime(record.start_time),
            end_time=self._optional_aware_datetime(record.end_time),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_dataset_quality_report(
        self, record: DatasetQualityReportRecord
    ) -> DatasetQualityReport:
        """Convert a dataset quality report row to a domain model.

        Args:
            record: Persisted dataset quality report row.

        Returns:
            Dataset quality report domain model.
        """

        return DatasetQualityReport(
            dataset_id=UUID(record.dataset_id),
            total_records=record.total_records,
            error_count=record.error_count,
            warning_count=record.warning_count,
            has_errors=record.has_errors,
            issues=[
                DatasetQualityIssue.model_validate(issue) for issue in record.issues
            ],
        )

    def _to_dataset_candle(self, record: DatasetCandleRecord) -> Candle:
        """Convert a dataset candle row to a domain model.

        Args:
            record: Persisted dataset candle row.

        Returns:
            Candle domain model.
        """

        return Candle(
            symbol=record.symbol,
            timeframe=record.timeframe,
            open_time=self._aware_datetime(record.open_time),
            close_time=self._aware_datetime(record.close_time),
            open=record.open,
            high=record.high,
            low=record.low,
            close=record.close,
            volume=record.volume,
            quote_volume=record.quote_volume,
            source=record.source,
            as_of=self._aware_datetime(record.as_of),
            fetched_at=self._optional_aware_datetime(record.fetched_at),
            ingestion_run_id=UUID(record.ingestion_run_id)
            if record.ingestion_run_id is not None
            else None,
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_raw_market_data_record(
        self, record: RawMarketDataRecordRow
    ) -> RawMarketDataRecord:
        """Convert a raw market data row to a domain model.

        Args:
            record: Persisted raw market data row.

        Returns:
            Raw market data record domain model.
        """

        return RawMarketDataRecord(
            raw_record_id=UUID(record.raw_record_id),
            dataset_id=UUID(record.dataset_id),
            ingestion_run_id=UUID(record.ingestion_run_id),
            source=cast(DatasetSource, record.source),
            source_uri=record.source_uri,
            row_index=record.row_index,
            payload=dict(record.payload),
            fetched_at=self._optional_aware_datetime(record.fetched_at),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_candle(self, record: CandleRecord) -> Candle:
        """Convert a candle row to a domain model.

        Args:
            record: Persisted candle row.

        Returns:
            Candle domain model.
        """

        return Candle(
            symbol=record.symbol,
            timeframe=record.timeframe,
            open_time=self._aware_datetime(record.open_time),
            close_time=self._aware_datetime(record.close_time),
            open=record.open,
            high=record.high,
            low=record.low,
            close=record.close,
            volume=record.volume,
            quote_volume=record.quote_volume,
            source=record.source,
            as_of=self._aware_datetime(record.as_of),
            fetched_at=self._optional_aware_datetime(record.fetched_at),
            ingestion_run_id=UUID(record.ingestion_run_id)
            if record.ingestion_run_id is not None
            else None,
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_orderbook_snapshot(
        self, record: OrderBookSnapshotRecord
    ) -> OrderBookSnapshot:
        """Convert an order book snapshot row to a domain model.

        Args:
            record: Persisted order book snapshot row.

        Returns:
            Order book snapshot domain model.
        """

        return OrderBookSnapshot(
            symbol=record.symbol,
            as_of=self._aware_datetime(record.as_of),
            bids=[
                (Decimal(price), Decimal(quantity)) for price, quantity in record.bids
            ],
            asks=[
                (Decimal(price), Decimal(quantity)) for price, quantity in record.asks
            ],
            mid_price=record.mid_price,
            spread_bps=record.spread_bps,
            depth_1pct_usd=record.depth_1pct_usd,
            source=record.source,
            sequence_number=record.sequence_number,
            checksum=record.checksum,
            expected_checksum=record.expected_checksum,
        )

    def _to_feature_snapshot(self, record: FeatureSnapshotRecord) -> FeatureSnapshot:
        """Convert a feature snapshot row to a domain model.

        Args:
            record: Persisted feature snapshot row.

        Returns:
            Feature snapshot domain model.
        """

        return FeatureSnapshot(
            snapshot_id=UUID(record.snapshot_id),
            run_id=UUID(record.run_id),
            symbol=record.symbol,
            as_of=self._aware_datetime(record.as_of),
            features=dict(record.features),
            source=record.source,
        )

    def _to_experiment(self, record: ExperimentRegistryRecord) -> ExperimentRecord:
        """Convert an experiment row to a domain model.

        Args:
            record: Persisted experiment row.

        Returns:
            Experiment domain model.
        """

        return ExperimentRecord(
            experiment_id=UUID(record.experiment_id),
            name=record.name,
            kind=cast(ExperimentKind, record.kind),
            hypothesis=record.hypothesis,
            dataset_id=UUID(record.dataset_id),
            model_id=UUID(record.model_id) if record.model_id else None,
            parameters=dict(record.parameters),
            status=cast(ExperimentStatus, record.status),
            metrics=dict(record.metrics),
            created_at=self._aware_datetime(record.created_at),
            queued_at=self._optional_aware_datetime(record.queued_at),
            completed_at=self._optional_aware_datetime(record.completed_at),
        )

    def _to_market_event(self, record: MarketEventRecord) -> MarketEvent:
        """Convert a market event row to a domain model.

        Args:
            record: Persisted market event row.

        Returns:
            Market event domain model.
        """

        return MarketEvent(
            event_id=UUID(record.event_id),
            type=cast(MarketEventType, record.type),
            symbol=record.symbol,
            simulated_time=self._aware_datetime(record.simulated_time),
            payload=dict(record.payload),
            source=record.source,
            confidence=record.confidence,
        )

    def _to_realtime_event(self, record: RealtimeEventRecord) -> dict[str, object]:
        """Convert a realtime event row to an envelope dictionary.

        Args:
            record: Persisted realtime event row.

        Returns:
            Realtime event envelope.
        """

        return {
            "event_id": record.event_id,
            "topic": record.topic,
            "run_id": record.run_id,
            "simulated_time": self._aware_datetime(record.simulated_time).isoformat(),
            "payload": dict(record.payload),
        }

    def _to_observation_snapshot(
        self, record: ObservationSnapshotRecord
    ) -> Observation:
        """Convert an observation snapshot row to a domain model.

        Args:
            record: Persisted observation snapshot row.

        Returns:
            Observation domain model.
        """

        return Observation.model_validate(record.payload)

    def _to_agent_run(self, record: AgentRunRecord) -> AgentRun:
        """Convert an agent run row to a domain model.

        Args:
            record: Persisted agent run row.

        Returns:
            Agent run domain model.
        """

        return AgentRun(
            agent_run_id=UUID(record.agent_run_id),
            run_id=UUID(record.run_id),
            decision_id=UUID(record.decision_id),
            agent_id=record.agent_id,
            status=cast(AgentRunStatus, record.status),
            started_at_sim_time=self._aware_datetime(record.started_at_sim_time),
            completed_at_sim_time=self._aware_datetime(record.completed_at_sim_time),
        )

    def _to_agent_message(self, record: AgentMessageRecord) -> AgentMessage:
        """Convert an agent message row to a domain model.

        Args:
            record: Persisted agent message row.

        Returns:
            Agent message domain model.
        """

        return AgentMessage(
            message_id=UUID(record.message_id),
            agent_run_id=UUID(record.agent_run_id),
            role=cast(AgentMessageRole, record.role),
            content=dict(record.content),
            created_at_sim_time=self._aware_datetime(record.created_at_sim_time),
        )

    def _to_decision(self, record: DecisionRecord) -> TradeIntent:
        """Convert a decision row to a domain model.

        Args:
            record: Persisted decision row.

        Returns:
            Trade intent domain model.
        """

        return TradeIntent(
            decision_id=UUID(record.decision_id),
            run_id=UUID(record.run_id),
            observation_id=UUID(record.observation_id),
            agent_run_id=UUID(record.agent_run_id),
            input_data_as_of=self._aware_datetime(record.input_data_as_of),
            agent_id=record.agent_id,
            symbol=record.symbol,
            market_type=cast(MarketType, record.market_type),
            action=cast(DecisionAction, record.action),
            target_weight=record.target_weight,
            target_notional=record.target_notional,
            max_leverage=record.max_leverage,
            confidence=record.confidence,
            expected_holding_period=record.expected_holding_period,
            thesis=record.thesis,
            evidence=[dict(item) for item in record.evidence],
            invalidation_conditions=list(record.invalidation_conditions),
            data_quality_score=record.data_quality_score,
            status=cast(DecisionStatus, record.status),
            created_at_sim_time=self._aware_datetime(record.created_at_sim_time),
        )

    def _to_risk_review(self, record: RiskReviewRecord) -> RiskReview:
        """Convert a risk review row to a domain model.

        Args:
            record: Persisted risk review row.

        Returns:
            Risk review domain model.
        """

        return RiskReview(
            review_id=UUID(record.review_id),
            decision_id=UUID(record.decision_id),
            status=cast(RiskStatus, record.status),
            original_target_weight=record.original_target_weight,
            approved_target_weight=record.approved_target_weight,
            max_order_notional=record.max_order_notional,
            reasons=list(record.reasons),
            triggered_rules=list(record.triggered_rules),
            created_at_sim_time=self._aware_datetime(record.created_at_sim_time),
        )

    def _to_decision_review(self, record: DecisionReviewRecord) -> DecisionReview:
        """Convert a decision review row to a domain model.

        Args:
            record: Persisted decision review row.

        Returns:
            Decision review domain model.
        """

        return DecisionReview(
            review_id=UUID(record.review_id),
            decision_id=UUID(record.decision_id),
            run_id=UUID(record.run_id),
            horizon=record.horizon,
            realized_return=record.realized_return,
            max_adverse_excursion=record.max_adverse_excursion,
            max_favorable_excursion=record.max_favorable_excursion,
            was_correct_directionally=record.was_correct_directionally,
            error_tags=list(record.error_tags),
            reviewer_summary=record.reviewer_summary,
            created_at_sim_time=self._aware_datetime(record.created_at_sim_time),
        )

    def _to_memory_entry(self, record: MemoryEntryRecord) -> MemoryEntry:
        """Convert a memory entry row to a domain model.

        Args:
            record: Persisted memory entry row.

        Returns:
            Memory entry domain model.
        """

        return MemoryEntry(
            memory_id=UUID(record.memory_id),
            run_id=UUID(record.run_id),
            decision_id=UUID(record.decision_id) if record.decision_id else None,
            memory_type=cast(MemoryType, record.memory_type),
            summary=record.summary,
            content=dict(record.content),
            tags=list(record.tags),
            available_at_sim_time=self._aware_datetime(record.available_at_sim_time),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_model_registry_entry(
        self, record: ModelRegistryRecord
    ) -> ModelRegistryEntry:
        """Convert a model registry row to a domain model.

        Args:
            record: Persisted model registry row.

        Returns:
            Model registry domain model.
        """

        return ModelRegistryEntry(
            model_id=UUID(record.model_id),
            name=record.name,
            version=record.version,
            model_type=cast(ModelType, record.model_type),
            algorithm=record.algorithm,
            training_dataset_id=UUID(record.training_dataset_id),
            validation_dataset_id=UUID(record.validation_dataset_id),
            metrics=dict(record.metrics),
            artifact_uri=record.artifact_uri,
            status=cast(ModelStatus, record.status),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_plugin_registry_entry(
        self, record: PluginRegistryRecord
    ) -> PluginRegistryEntry:
        """Convert a plugin registry row to a domain model.

        Args:
            record: Persisted plugin registry row.

        Returns:
            Plugin registry domain model.
        """

        return PluginRegistryEntry(
            plugin_id=UUID(record.plugin_id),
            manifest=PluginManifest.model_validate(record.manifest),
            sandbox_result=SandboxResult.model_validate(record.sandbox_result),
            status=cast(PluginStatus, record.status),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_report(self, record: ReportRecord) -> ReportArtifact:
        """Convert a report row to a domain model.

        Args:
            record: Persisted report row.

        Returns:
            Report artifact domain model.
        """

        return ReportArtifact(
            report_id=UUID(record.report_id),
            run_id=UUID(record.run_id),
            report_type=cast(ReportType, record.report_type),
            title=record.title,
            summary=record.summary,
            sections=dict(record.sections),
            created_at_sim_time=self._aware_datetime(record.created_at_sim_time),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_alert(self, record: AlertRecord) -> Alert:
        """Convert an alert row to a domain model.

        Args:
            record: Persisted alert row.

        Returns:
            Alert domain model.
        """

        return Alert(
            alert_id=UUID(record.alert_id),
            run_id=UUID(record.run_id),
            category=cast(AlertCategory, record.category),
            severity=cast(AlertSeverity, record.severity),
            message=record.message,
            status=cast(AlertStatus, record.status),
            created_at_sim_time=self._aware_datetime(record.created_at_sim_time),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_order(self, record: OrderRecord) -> SimOrder:
        """Convert an order row to a domain model.

        Args:
            record: Persisted order row.

        Returns:
            Simulated order domain model.
        """

        return SimOrder(
            order_id=UUID(record.order_id),
            run_id=UUID(record.run_id),
            account_id=UUID(record.account_id),
            decision_id=UUID(record.decision_id) if record.decision_id else None,
            symbol=record.symbol,
            side=cast(OrderSide, record.side),
            order_type=cast(OrderType, record.order_type),
            quantity=record.quantity,
            limit_price=record.limit_price,
            status=cast(OrderStatus, record.status),
            submitted_at_sim_time=self._aware_datetime(record.submitted_at_sim_time),
            updated_at_sim_time=self._aware_datetime(record.updated_at_sim_time),
        )

    def _to_fill(self, record: FillRecord) -> Fill:
        """Convert a fill row to a domain model.

        Args:
            record: Persisted fill row.

        Returns:
            Fill domain model.
        """

        return Fill(
            fill_id=UUID(record.fill_id),
            order_id=UUID(record.order_id),
            run_id=UUID(record.run_id),
            symbol=record.symbol,
            side=cast(OrderSide, record.side),
            quantity=record.quantity,
            price=record.price,
            fee=record.fee,
            slippage_bps=record.slippage_bps,
            filled_at_sim_time=self._aware_datetime(record.filled_at_sim_time),
        )

    def _to_ledger_entry(self, record: LedgerEntryRecord) -> LedgerEntry:
        """Convert a ledger entry row to a domain model.

        Args:
            record: Persisted ledger entry row.

        Returns:
            Ledger entry domain model.
        """

        return LedgerEntry(
            ledger_entry_id=UUID(record.ledger_entry_id),
            run_id=UUID(record.run_id),
            account_id=UUID(record.account_id),
            fill_id=UUID(record.fill_id) if record.fill_id else None,
            entry_type=cast(LedgerEntryType, record.entry_type),
            symbol=record.symbol,
            quantity=record.quantity,
            price=record.price,
            notional=record.notional,
            cash_delta=record.cash_delta,
            fee=record.fee,
            realized_pnl_delta=record.realized_pnl_delta,
            created_at_sim_time=self._aware_datetime(record.created_at_sim_time),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_portfolio_snapshot(
        self, record: PortfolioSnapshotRecord
    ) -> PortfolioSnapshot:
        """Convert a portfolio snapshot row to a domain model.

        Args:
            record: Persisted portfolio snapshot row.

        Returns:
            Portfolio snapshot domain model.
        """

        return PortfolioSnapshot(
            snapshot_id=UUID(record.snapshot_id),
            run_id=UUID(record.run_id),
            account_id=UUID(record.account_id),
            simulated_time=self._aware_datetime(record.simulated_time),
            cash_balance=record.cash_balance,
            total_equity=record.total_equity,
            realized_pnl=record.realized_pnl,
            unrealized_pnl=record.unrealized_pnl,
            max_drawdown=record.max_drawdown,
            gross_exposure=record.gross_exposure,
            net_exposure=record.net_exposure,
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_metric_snapshot(self, record: MetricSnapshotRecord) -> MetricSnapshot:
        """Convert a metric snapshot row to a domain model.

        Args:
            record: Persisted metric snapshot row.

        Returns:
            Metric snapshot domain model.
        """

        return MetricSnapshot(
            snapshot_id=UUID(record.snapshot_id),
            run_id=UUID(record.run_id),
            simulated_time=self._aware_datetime(record.simulated_time),
            metrics=dict(record.metrics),
            created_at=self._aware_datetime(record.created_at),
        )

    def _optional_aware_datetime(self, value: datetime | None) -> datetime | None:
        """Return an aware timestamp when a value is present.

        Args:
            value: Optional timestamp value.

        Returns:
            Timezone-aware timestamp or `None`.
        """

        if value is None:
            return None
        return self._aware_datetime(value)

    def _aware_datetime(self, value: datetime) -> datetime:
        """Return a timezone-aware timestamp.

        Args:
            value: Timestamp loaded from the database.

        Returns:
            Timestamp with UTC timezone when the database returned a naive value.
        """

        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value

    def _read_realtime_envelope_string(
        self,
        envelope: dict[str, object],
        key: str,
    ) -> str:
        """Read a required realtime envelope string value.

        Args:
            envelope: Realtime event envelope.
            key: Required key.

        Returns:
            Non-empty string value.

        Raises:
            ValueError: If the value is missing or empty.
        """

        value = envelope.get(key)
        if value is None:
            raise ValueError(f"Realtime envelope field {key} is required.")
        text = str(value)
        if not text:
            raise ValueError(f"Realtime envelope field {key} must not be empty.")
        return text

    def _read_realtime_envelope_time(
        self,
        envelope: dict[str, object],
    ) -> datetime:
        """Read the required realtime envelope simulated time.

        Args:
            envelope: Realtime event envelope.

        Returns:
            Simulated event timestamp.

        Raises:
            ValueError: If the timestamp is missing or invalid.
        """

        value = envelope.get("simulated_time")
        if isinstance(value, datetime):
            return value
        if isinstance(value, str):
            return datetime.fromisoformat(value.replace("Z", "+00:00"))
        raise ValueError("Realtime envelope field simulated_time is required.")

    def _read_realtime_envelope_payload(
        self,
        envelope: dict[str, object],
    ) -> dict[str, object]:
        """Read the required realtime envelope payload.

        Args:
            envelope: Realtime event envelope.

        Returns:
            Realtime event payload.

        Raises:
            ValueError: If the payload is missing or not an object.
        """

        value = envelope.get("payload")
        if not isinstance(value, dict):
            raise ValueError("Realtime envelope field payload must be an object.")
        return value
