"""Repository mappings between ORM rows and simulation domain models."""

from datetime import UTC, datetime
from typing import Literal, cast
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session, sessionmaker

from tiko.db.models import (
    AccountRecord,
    CandleRecord,
    DecisionRecord,
    FillRecord,
    MarketEventRecord,
    OrderRecord,
    RiskReviewRecord,
    SimulationRunRecord,
)
from tiko.domain.account import SimAccount
from tiko.domain.decision import TradeIntent
from tiko.domain.market import Candle, MarketEvent
from tiko.domain.order import Fill, SimOrder
from tiko.domain.risk import RiskReview
from tiko.domain.simulation import SimulationRun
from tiko.simulation.state import SimulationStepResult

SimulationRunStatus = Literal["created", "running", "paused", "stopped", "completed"]
SimulationMode = Literal[
    "historical_replay", "live_simulated_clock", "synthetic_market"
]
AccountStatus = Literal["active", "paused", "liquidated", "stopped"]
MarketEventType = Literal[
    "candle_closed",
    "tick",
    "orderbook_snapshot",
    "funding_update",
    "news_event",
    "liquidity_shock",
    "volatility_shock",
    "system_event",
]
MarketType = Literal["spot", "perp", "synthetic"]
DecisionAction = Literal[
    "open_long",
    "open_short",
    "increase_long",
    "increase_short",
    "reduce_long",
    "reduce_short",
    "close_position",
    "hold",
    "rebalance",
]
RiskStatus = Literal["approved", "rejected", "resized", "circuit_blocked"]
OrderSide = Literal["buy", "sell"]
OrderType = Literal["market", "limit"]
OrderStatus = Literal[
    "created",
    "submitted",
    "accepted",
    "rejected",
    "open",
    "partially_filled",
    "filled",
    "canceled",
    "expired",
]


class SimulationRepository:
    """Persist and load simulation artifacts through SQLAlchemy sessions."""

    def __init__(self, session_factory: sessionmaker[Session]) -> None:
        """Initialize the repository.

        Args:
            session_factory: SQLAlchemy session factory.
        """

        self._session_factory = session_factory

    def save_run(self, run: SimulationRun) -> None:
        """Persist a simulation run and its nested account state.

        Args:
            run: Simulation run to persist.
        """

        with self._session_factory() as session:
            self._merge_run(session, run)
            session.commit()

    def save_step_result(self, result: SimulationStepResult) -> None:
        """Persist all durable artifacts generated by one simulation step.

        Args:
            result: Simulation step output to persist.
        """

        with self._session_factory() as session:
            self._merge_run(session, result.run)
            self._add_candle(session, result.run.run_id, result.candle)
            self._merge_market_event(session, result.run.run_id, result.event)
            self._merge_decision(session, result.decision)
            self._merge_risk_review(session, result.run.run_id, result.risk_review)
            if result.order is not None:
                self._merge_order(session, result.order)
            if result.fill is not None:
                self._merge_fill(session, result.fill)
            session.commit()

    def get_run(self, run_id: UUID) -> SimulationRun | None:
        """Load one simulation run by ID.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Simulation run or `None`.
        """

        with self._session_factory() as session:
            run_record = session.get(SimulationRunRecord, str(run_id))
            if run_record is None:
                return None
            account_record = self._require_account(session, run_record.account_id)
            return self._to_run(run_record, account_record)

    def list_runs(self) -> list[SimulationRun]:
        """List persisted simulation runs ordered by creation time.

        Returns:
            Persisted simulation runs.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(SimulationRunRecord).order_by(SimulationRunRecord.created_at)
            ).all()
            return [
                self._to_run(record, self._require_account(session, record.account_id))
                for record in records
            ]

    def list_candles(self, run_id: UUID) -> list[Candle]:
        """List candles persisted for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Persisted candles in close-time order.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(CandleRecord)
                .where(CandleRecord.run_id == str(run_id))
                .order_by(CandleRecord.close_time)
            ).all()
            return [self._to_candle(record) for record in records]

    def list_market_events(self, run_id: UUID) -> list[MarketEvent]:
        """List market events persisted for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Persisted market events in simulated-time order.
        """

        with self._session_factory() as session:
            records = session.scalars(
                select(MarketEventRecord)
                .where(MarketEventRecord.run_id == str(run_id))
                .order_by(MarketEventRecord.simulated_time)
            ).all()
            return [self._to_market_event(record) for record in records]

    def list_decisions(self, run_id: UUID | None = None) -> list[TradeIntent]:
        """List persisted trade intents.

        Args:
            run_id: Optional simulation run filter.

        Returns:
            Persisted trade intents.
        """

        with self._session_factory() as session:
            statement = select(DecisionRecord).order_by(
                DecisionRecord.created_at_sim_time
            )
            if run_id is not None:
                statement = statement.where(DecisionRecord.run_id == str(run_id))
            records = session.scalars(statement).all()
            return [self._to_decision(record) for record in records]

    def list_orders(self, run_id: UUID | None = None) -> list[SimOrder]:
        """List persisted simulated orders.

        Args:
            run_id: Optional simulation run filter.

        Returns:
            Persisted simulated orders.
        """

        with self._session_factory() as session:
            statement = select(OrderRecord).order_by(OrderRecord.submitted_at_sim_time)
            if run_id is not None:
                statement = statement.where(OrderRecord.run_id == str(run_id))
            records = session.scalars(statement).all()
            return [self._to_order(record) for record in records]

    def list_fills(self, run_id: UUID | None = None) -> list[Fill]:
        """List persisted simulated fills.

        Args:
            run_id: Optional simulation run filter.

        Returns:
            Persisted simulated fills.
        """

        with self._session_factory() as session:
            statement = select(FillRecord).order_by(FillRecord.filled_at_sim_time)
            if run_id is not None:
                statement = statement.where(FillRecord.run_id == str(run_id))
            records = session.scalars(statement).all()
            return [self._to_fill(record) for record in records]

    def get_latest_risk_review(self, run_id: UUID) -> RiskReview | None:
        """Load the latest persisted risk review for a simulation run.

        Args:
            run_id: Simulation run identifier.

        Returns:
            Latest risk review or `None`.
        """

        with self._session_factory() as session:
            record = session.scalars(
                select(RiskReviewRecord)
                .where(RiskReviewRecord.run_id == str(run_id))
                .order_by(RiskReviewRecord.created_at_sim_time.desc())
            ).first()
            if record is None:
                return None
            return self._to_risk_review(record)

    def _merge_run(self, session: Session, run: SimulationRun) -> None:
        """Merge a run and its account into the active session.

        Args:
            session: Active SQLAlchemy session.
            run: Simulation run to merge.
        """

        self._merge_account(session, run.account)
        session.merge(
            SimulationRunRecord(
                run_id=str(run.run_id),
                name=run.name,
                status=run.status,
                mode=run.mode,
                account_id=str(run.account.account_id),
                symbols=run.symbols,
                start_sim_time=run.start_sim_time,
                current_sim_time=run.current_sim_time,
                end_sim_time=run.end_sim_time,
                speed_multiplier=run.speed_multiplier,
                config=run.config,
                created_at=run.created_at,
            )
        )

    def _merge_account(self, session: Session, account: SimAccount) -> None:
        """Merge an account into the active session.

        Args:
            session: Active SQLAlchemy session.
            account: Simulated account to merge.
        """

        session.merge(
            AccountRecord(
                account_id=str(account.account_id),
                name=account.name,
                base_currency=account.base_currency,
                initial_equity=account.initial_equity,
                cash_balance=account.cash_balance,
                total_equity=account.total_equity,
                realized_pnl=account.realized_pnl,
                unrealized_pnl=account.unrealized_pnl,
                max_drawdown=account.max_drawdown,
                status=account.status,
            )
        )

    def _add_candle(self, session: Session, run_id: UUID, candle: Candle) -> None:
        """Add a candle row for a simulation run.

        Args:
            session: Active SQLAlchemy session.
            run_id: Simulation run identifier.
            candle: Candle to persist.
        """

        session.add(
            CandleRecord(
                run_id=str(run_id),
                symbol=candle.symbol,
                timeframe=candle.timeframe,
                open_time=candle.open_time,
                close_time=candle.close_time,
                open=candle.open,
                high=candle.high,
                low=candle.low,
                close=candle.close,
                volume=candle.volume,
                quote_volume=candle.quote_volume,
                source=candle.source,
                as_of=candle.as_of,
                created_at=candle.created_at,
            )
        )

    def _merge_market_event(
        self, session: Session, run_id: UUID, event: MarketEvent
    ) -> None:
        """Merge a market event into the active session.

        Args:
            session: Active SQLAlchemy session.
            run_id: Simulation run identifier.
            event: Market event to merge.
        """

        session.merge(
            MarketEventRecord(
                event_id=str(event.event_id),
                run_id=str(run_id),
                type=event.type,
                symbol=event.symbol,
                simulated_time=event.simulated_time,
                payload=event.payload,
                source=event.source,
                confidence=event.confidence,
            )
        )

    def _merge_decision(self, session: Session, decision: TradeIntent) -> None:
        """Merge a trade intent into the active session.

        Args:
            session: Active SQLAlchemy session.
            decision: Trade intent to merge.
        """

        session.merge(
            DecisionRecord(
                decision_id=str(decision.decision_id),
                run_id=str(decision.run_id),
                agent_id=decision.agent_id,
                symbol=decision.symbol,
                market_type=decision.market_type,
                action=decision.action,
                target_weight=decision.target_weight,
                target_notional=decision.target_notional,
                max_leverage=decision.max_leverage,
                confidence=decision.confidence,
                expected_holding_period=decision.expected_holding_period,
                thesis=decision.thesis,
                evidence=decision.evidence,
                invalidation_conditions=decision.invalidation_conditions,
                data_quality_score=decision.data_quality_score,
                created_at_sim_time=decision.created_at_sim_time,
            )
        )

    def _merge_risk_review(
        self, session: Session, run_id: UUID, review: RiskReview
    ) -> None:
        """Merge a risk review into the active session.

        Args:
            session: Active SQLAlchemy session.
            run_id: Simulation run identifier.
            review: Risk review to merge.
        """

        session.merge(
            RiskReviewRecord(
                review_id=str(review.review_id),
                run_id=str(run_id),
                decision_id=str(review.decision_id),
                status=review.status,
                original_target_weight=review.original_target_weight,
                approved_target_weight=review.approved_target_weight,
                max_order_notional=review.max_order_notional,
                reasons=review.reasons,
                triggered_rules=review.triggered_rules,
                created_at_sim_time=review.created_at_sim_time,
            )
        )

    def _merge_order(self, session: Session, order: SimOrder) -> None:
        """Merge a simulated order into the active session.

        Args:
            session: Active SQLAlchemy session.
            order: Simulated order to merge.
        """

        session.merge(
            OrderRecord(
                order_id=str(order.order_id),
                run_id=str(order.run_id),
                account_id=str(order.account_id),
                decision_id=str(order.decision_id) if order.decision_id else None,
                symbol=order.symbol,
                side=order.side,
                order_type=order.order_type,
                quantity=order.quantity,
                limit_price=order.limit_price,
                status=order.status,
                submitted_at_sim_time=order.submitted_at_sim_time,
                updated_at_sim_time=order.updated_at_sim_time,
            )
        )

    def _merge_fill(self, session: Session, fill: Fill) -> None:
        """Merge a simulated fill into the active session.

        Args:
            session: Active SQLAlchemy session.
            fill: Simulated fill to merge.
        """

        session.merge(
            FillRecord(
                fill_id=str(fill.fill_id),
                order_id=str(fill.order_id),
                run_id=str(fill.run_id),
                symbol=fill.symbol,
                side=fill.side,
                quantity=fill.quantity,
                price=fill.price,
                fee=fill.fee,
                slippage_bps=fill.slippage_bps,
                filled_at_sim_time=fill.filled_at_sim_time,
            )
        )

    def _require_account(self, session: Session, account_id: str) -> AccountRecord:
        """Load an account or fail when persisted run state is inconsistent.

        Args:
            session: Active SQLAlchemy session.
            account_id: Account identifier.

        Returns:
            Persisted account record.

        Raises:
            LookupError: If the account row is missing.
        """

        record = session.get(AccountRecord, account_id)
        if record is None:
            raise LookupError(f"Missing account row {account_id}.")
        return record

    def _to_run(
        self, record: SimulationRunRecord, account_record: AccountRecord
    ) -> SimulationRun:
        """Convert a run row and account row to a domain model.

        Args:
            record: Persisted run row.
            account_record: Persisted account row.

        Returns:
            Simulation run domain model.
        """

        return SimulationRun(
            run_id=UUID(record.run_id),
            name=record.name,
            status=cast(SimulationRunStatus, record.status),
            mode=cast(SimulationMode, record.mode),
            account=self._to_account(account_record),
            symbols=list(record.symbols),
            start_sim_time=self._aware_datetime(record.start_sim_time),
            current_sim_time=self._aware_datetime(record.current_sim_time),
            end_sim_time=self._optional_aware_datetime(record.end_sim_time),
            speed_multiplier=record.speed_multiplier,
            config=dict(record.config),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_account(self, record: AccountRecord) -> SimAccount:
        """Convert an account row to a domain model.

        Args:
            record: Persisted account row.

        Returns:
            Simulated account domain model.
        """

        return SimAccount(
            account_id=UUID(record.account_id),
            name=record.name,
            base_currency=record.base_currency,
            initial_equity=record.initial_equity,
            cash_balance=record.cash_balance,
            total_equity=record.total_equity,
            realized_pnl=record.realized_pnl,
            unrealized_pnl=record.unrealized_pnl,
            max_drawdown=record.max_drawdown,
            status=cast(AccountStatus, record.status),
        )

    def _to_candle(self, record: CandleRecord) -> Candle:
        """Convert a candle row to a domain model.

        Args:
            record: Persisted candle row.

        Returns:
            Candle domain model.
        """

        return Candle(
            symbol=record.symbol,
            timeframe=record.timeframe,
            open_time=self._aware_datetime(record.open_time),
            close_time=self._aware_datetime(record.close_time),
            open=record.open,
            high=record.high,
            low=record.low,
            close=record.close,
            volume=record.volume,
            quote_volume=record.quote_volume,
            source=record.source,
            as_of=self._aware_datetime(record.as_of),
            created_at=self._aware_datetime(record.created_at),
        )

    def _to_market_event(self, record: MarketEventRecord) -> MarketEvent:
        """Convert a market event row to a domain model.

        Args:
            record: Persisted market event row.

        Returns:
            Market event domain model.
        """

        return MarketEvent(
            event_id=UUID(record.event_id),
            type=cast(MarketEventType, record.type),
            symbol=record.symbol,
            simulated_time=self._aware_datetime(record.simulated_time),
            payload=dict(record.payload),
            source=record.source,
            confidence=record.confidence,
        )

    def _to_decision(self, record: DecisionRecord) -> TradeIntent:
        """Convert a decision row to a domain model.

        Args:
            record: Persisted decision row.

        Returns:
            Trade intent domain model.
        """

        return TradeIntent(
            decision_id=UUID(record.decision_id),
            run_id=UUID(record.run_id),
            agent_id=record.agent_id,
            symbol=record.symbol,
            market_type=cast(MarketType, record.market_type),
            action=cast(DecisionAction, record.action),
            target_weight=record.target_weight,
            target_notional=record.target_notional,
            max_leverage=record.max_leverage,
            confidence=record.confidence,
            expected_holding_period=record.expected_holding_period,
            thesis=record.thesis,
            evidence=[dict(item) for item in record.evidence],
            invalidation_conditions=list(record.invalidation_conditions),
            data_quality_score=record.data_quality_score,
            created_at_sim_time=self._aware_datetime(record.created_at_sim_time),
        )

    def _to_risk_review(self, record: RiskReviewRecord) -> RiskReview:
        """Convert a risk review row to a domain model.

        Args:
            record: Persisted risk review row.

        Returns:
            Risk review domain model.
        """

        return RiskReview(
            review_id=UUID(record.review_id),
            decision_id=UUID(record.decision_id),
            status=cast(RiskStatus, record.status),
            original_target_weight=record.original_target_weight,
            approved_target_weight=record.approved_target_weight,
            max_order_notional=record.max_order_notional,
            reasons=list(record.reasons),
            triggered_rules=list(record.triggered_rules),
            created_at_sim_time=self._aware_datetime(record.created_at_sim_time),
        )

    def _to_order(self, record: OrderRecord) -> SimOrder:
        """Convert an order row to a domain model.

        Args:
            record: Persisted order row.

        Returns:
            Simulated order domain model.
        """

        return SimOrder(
            order_id=UUID(record.order_id),
            run_id=UUID(record.run_id),
            account_id=UUID(record.account_id),
            decision_id=UUID(record.decision_id) if record.decision_id else None,
            symbol=record.symbol,
            side=cast(OrderSide, record.side),
            order_type=cast(OrderType, record.order_type),
            quantity=record.quantity,
            limit_price=record.limit_price,
            status=cast(OrderStatus, record.status),
            submitted_at_sim_time=self._aware_datetime(record.submitted_at_sim_time),
            updated_at_sim_time=self._aware_datetime(record.updated_at_sim_time),
        )

    def _to_fill(self, record: FillRecord) -> Fill:
        """Convert a fill row to a domain model.

        Args:
            record: Persisted fill row.

        Returns:
            Fill domain model.
        """

        return Fill(
            fill_id=UUID(record.fill_id),
            order_id=UUID(record.order_id),
            run_id=UUID(record.run_id),
            symbol=record.symbol,
            side=cast(OrderSide, record.side),
            quantity=record.quantity,
            price=record.price,
            fee=record.fee,
            slippage_bps=record.slippage_bps,
            filled_at_sim_time=self._aware_datetime(record.filled_at_sim_time),
        )

    def _optional_aware_datetime(self, value: datetime | None) -> datetime | None:
        """Return an aware timestamp when a value is present.

        Args:
            value: Optional timestamp value.

        Returns:
            Timezone-aware timestamp or `None`.
        """

        if value is None:
            return None
        return self._aware_datetime(value)

    def _aware_datetime(self, value: datetime) -> datetime:
        """Return a timezone-aware timestamp.

        Args:
            value: Timestamp loaded from the database.

        Returns:
            Timestamp with UTC timezone when the database returned a naive value.
        """

        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value
