"""Portfolio sizing service for approved simulated trade intent."""

from collections.abc import Sequence
from decimal import ROUND_DOWN, Decimal
from typing import Literal

from tiko.domain.account import Position, SimAccount
from tiko.domain.decision import TradeIntent
from tiko.domain.order import OrderRequest
from tiko.domain.portfolio import PortfolioOrderPlan
from tiko.domain.risk import RiskReview

PortfolioOrderType = Literal["market", "limit"]
SUPPORTED_PORTFOLIO_ORDER_TYPES: tuple[PortfolioOrderType, ...] = ("market", "limit")


class PortfolioService:
    """Convert approved target exposure into internal simulated orders."""

    def __init__(
        self,
        lot_size: Decimal = Decimal("0.000001"),
        min_order_notional: Decimal = Decimal("0"),
        taker_fee_bps: Decimal = Decimal("5"),
        maker_fee_bps: Decimal | None = None,
        estimated_slippage_bps: Decimal = Decimal("2"),
        order_type: PortfolioOrderType = "market",
    ) -> None:
        """Initialize sizing precision.

        Args:
            lot_size: Quantity precision used for simulated orders.
            min_order_notional: Minimum executable order notional.
            taker_fee_bps: Estimated taker fee in basis points.
            maker_fee_bps: Estimated maker fee in basis points.
            estimated_slippage_bps: Estimated market slippage in basis points.
            order_type: Simulated order type generated by approved plans.

        Raises:
            ValueError: If a threshold or order type is unsupported.
        """

        if min_order_notional < Decimal("0"):
            raise ValueError("min_order_notional must not be negative.")
        if order_type not in SUPPORTED_PORTFOLIO_ORDER_TYPES:
            raise ValueError("Portfolio order_type must be market or limit.")
        self.lot_size = lot_size
        self.min_order_notional = min_order_notional
        self.taker_fee_bps = taker_fee_bps
        self.maker_fee_bps = (
            maker_fee_bps if maker_fee_bps is not None else taker_fee_bps
        )
        self.estimated_slippage_bps = estimated_slippage_bps
        self.order_type = order_type

    def create_order_plan(
        self,
        account: SimAccount,
        intent: TradeIntent,
        risk_review: RiskReview,
        reference_price: Decimal,
        positions: Sequence[Position] = (),
        min_order_notional: Decimal | None = None,
    ) -> PortfolioOrderPlan:
        """Create a portfolio order sizing plan.

        Args:
            account: Current simulated account.
            intent: Structured trade intent.
            risk_review: Independent risk review.
            reference_price: Current market reference price.
            positions: Current simulated positions used for target-delta sizing.
            min_order_notional: Optional minimum notional override.

        Returns:
            Portfolio sizing plan with optional order request.

        Raises:
            ValueError: If the minimum notional override is negative.
        """

        effective_min_order_notional = self._resolve_min_order_notional(
            min_order_notional
        )
        target_notional = risk_review.approved_target_weight * account.total_equity
        current_notional = self._current_signed_notional(intent.symbol, positions)
        delta_notional = target_notional - current_notional
        if risk_review.status not in {"approved", "resized"}:
            return self._build_no_order_plan(
                account=account,
                intent=intent,
                reason="risk_review_not_executable",
                sizing_explanation=(
                    f"Risk review status {risk_review.status} cannot create orders."
                ),
                target_notional=target_notional,
                current_notional=current_notional,
                delta_notional=delta_notional,
                approved_delta_notional=Decimal("0"),
                reference_price=reference_price,
            )
        approved_delta_notional = delta_notional
        if abs(delta_notional) > risk_review.max_order_notional:
            approved_delta_notional = (
                risk_review.max_order_notional
                if delta_notional > Decimal("0")
                else -risk_review.max_order_notional
            )
        if approved_delta_notional == Decimal("0"):
            return self._build_no_order_plan(
                account=account,
                intent=intent,
                reason="target_exposure_already_met",
                sizing_explanation="Current exposure already matches target exposure.",
                target_notional=target_notional,
                current_notional=current_notional,
                delta_notional=delta_notional,
                approved_delta_notional=approved_delta_notional,
                reference_price=reference_price,
            )
        quantity = (abs(approved_delta_notional) / reference_price).quantize(
            self.lot_size, rounding=ROUND_DOWN
        )
        if quantity <= Decimal("0"):
            return self._build_no_order_plan(
                account=account,
                intent=intent,
                reason="quantity_below_lot_size",
                sizing_explanation="Rounded order quantity is below lot size.",
                target_notional=target_notional,
                current_notional=current_notional,
                delta_notional=delta_notional,
                approved_delta_notional=approved_delta_notional,
                reference_price=reference_price,
            )
        expected_notional = quantity * reference_price
        if (
            effective_min_order_notional > Decimal("0")
            and expected_notional < effective_min_order_notional
        ):
            return self._build_no_order_plan(
                account=account,
                intent=intent,
                reason="notional_below_minimum",
                sizing_explanation=(
                    f"Expected notional {expected_notional} is below minimum "
                    f"order notional {effective_min_order_notional}."
                ),
                target_notional=target_notional,
                current_notional=current_notional,
                delta_notional=delta_notional,
                approved_delta_notional=approved_delta_notional,
                reference_price=reference_price,
            )
        order_request = OrderRequest(
            run_id=intent.run_id,
            account_id=account.account_id,
            decision_id=intent.decision_id,
            symbol=intent.symbol,
            side="buy" if approved_delta_notional > Decimal("0") else "sell",
            order_type=self.order_type,
            quantity=quantity,
            limit_price=self._create_limit_price(reference_price),
            submitted_at_sim_time=intent.created_at_sim_time,
        )
        return PortfolioOrderPlan(
            run_id=intent.run_id,
            account_id=account.account_id,
            decision_id=intent.decision_id,
            symbol=intent.symbol,
            status="order_created",
            reason=None,
            sizing_explanation=(
                f"Target notional {target_notional}; current notional "
                f"{current_notional}; approved delta {approved_delta_notional}; "
                f"rounded quantity {quantity} at reference price {reference_price}."
            ),
            target_notional=target_notional,
            current_notional=current_notional,
            delta_notional=delta_notional,
            approved_delta_notional=approved_delta_notional,
            reference_price=reference_price,
            quantity=quantity,
            expected_notional=expected_notional,
            estimated_fee=self._estimate_fee(expected_notional, self.order_type),
            estimated_slippage_bps=self.estimated_slippage_bps,
            order_request=order_request,
        )

    def create_order_request(
        self,
        account: SimAccount,
        intent: TradeIntent,
        risk_review: RiskReview,
        reference_price: Decimal,
        positions: Sequence[Position] = (),
        min_order_notional: Decimal | None = None,
    ) -> OrderRequest | None:
        """Create an internal order request for an approved risk review.

        Args:
            account: Current simulated account.
            intent: Structured trade intent.
            risk_review: Independent risk review.
            reference_price: Current market reference price.
            positions: Current simulated positions used for target-delta sizing.
            min_order_notional: Optional minimum notional override.

        Returns:
            Simulated order request or `None` when no order should be created.
        """

        return self.create_order_plan(
            account=account,
            intent=intent,
            risk_review=risk_review,
            reference_price=reference_price,
            positions=positions,
            min_order_notional=min_order_notional,
        ).order_request

    def _build_no_order_plan(
        self,
        account: SimAccount,
        intent: TradeIntent,
        reason: str,
        sizing_explanation: str,
        target_notional: Decimal,
        current_notional: Decimal,
        delta_notional: Decimal,
        approved_delta_notional: Decimal,
        reference_price: Decimal,
    ) -> PortfolioOrderPlan:
        """Build a no-order portfolio plan.

        Args:
            account: Current simulated account.
            intent: Structured trade intent.
            reason: Machine-readable no-order reason.
            sizing_explanation: Human-readable sizing explanation.
            target_notional: Signed target notional.
            current_notional: Signed current notional.
            delta_notional: Signed raw delta notional.
            approved_delta_notional: Signed executable delta notional.
            reference_price: Current market reference price.

        Returns:
            Portfolio plan without an order request.
        """

        return PortfolioOrderPlan(
            run_id=intent.run_id,
            account_id=account.account_id,
            decision_id=intent.decision_id,
            symbol=intent.symbol,
            status="no_order",
            reason=reason,
            sizing_explanation=sizing_explanation,
            target_notional=target_notional,
            current_notional=current_notional,
            delta_notional=delta_notional,
            approved_delta_notional=approved_delta_notional,
            reference_price=reference_price,
            quantity=Decimal("0"),
            expected_notional=Decimal("0"),
            estimated_fee=Decimal("0"),
            estimated_slippage_bps=Decimal("0"),
            order_request=None,
        )

    def _create_limit_price(self, reference_price: Decimal) -> Decimal | None:
        """Create a deterministic limit price for configured limit orders.

        Args:
            reference_price: Current market reference price.

        Returns:
            Reference price for limit orders or `None` for market orders.
        """

        if self.order_type == "limit":
            return reference_price
        return None

    def _resolve_min_order_notional(
        self, min_order_notional: Decimal | None
    ) -> Decimal:
        """Resolve the effective minimum order notional for one plan.

        Args:
            min_order_notional: Optional minimum notional override.

        Returns:
            Effective minimum order notional.

        Raises:
            ValueError: If the override is negative.
        """

        if min_order_notional is None:
            return self.min_order_notional
        if min_order_notional < Decimal("0"):
            raise ValueError("min_order_notional must not be negative.")
        return min_order_notional

    def _estimate_fee(
        self, expected_notional: Decimal, order_type: PortfolioOrderType
    ) -> Decimal:
        """Estimate taker fee for an expected order notional.

        Args:
            expected_notional: Absolute expected order notional.
            order_type: Simulated order type used for fee-rate selection.

        Returns:
            Estimated fee amount.
        """

        fee_bps = self.maker_fee_bps if order_type == "limit" else self.taker_fee_bps
        return expected_notional * fee_bps / Decimal("10000")

    def _current_signed_notional(
        self,
        symbol: str,
        positions: Sequence[Position],
    ) -> Decimal:
        """Calculate current signed notional for one symbol.

        Args:
            symbol: Symbol to match.
            positions: Current simulated positions.

        Returns:
            Signed notional where longs are positive and shorts are negative.
        """

        return sum(
            (
                position.notional if position.side == "long" else -position.notional
                for position in positions
                if position.symbol == symbol and position.side != "flat"
            ),
            Decimal("0"),
        )
