"""Internal simulated broker and matching behavior."""

from decimal import Decimal

from tiko.domain.order import Fill, OrderRequest, SimOrder
from tiko.simulation.fee import FeeEngine
from tiko.simulation.matching import MatchingEngine, TimeInForce
from tiko.simulation.slippage import SlippageContext, SlippageEngine


class SimBroker:
    """Convert internal order requests into immediate simulated fills."""

    def __init__(
        self,
        fee_bps: Decimal = Decimal("5"),
        slippage_bps: Decimal = Decimal("2"),
        maker_fee_bps: Decimal | None = None,
        slippage_volatility_multiplier: Decimal = Decimal("0.2"),
        slippage_liquidity_multiplier: Decimal = Decimal("1.5"),
        max_market_spread_bps: Decimal = Decimal("100"),
        min_market_depth_1pct_usd: Decimal = Decimal("0"),
        matching_engine: MatchingEngine | None = None,
    ) -> None:
        """Initialize broker fee and slippage parameters.

        Args:
            fee_bps: Simulated taker fee in basis points.
            slippage_bps: Simulated slippage in basis points.
            maker_fee_bps: Optional simulated maker fee in basis points.
            slippage_volatility_multiplier: Weight applied to volatility slippage.
            slippage_liquidity_multiplier: Weight applied to liquidity slippage.
            max_market_spread_bps: Maximum acceptable market spread.
            min_market_depth_1pct_usd: Minimum acceptable 1% depth in USD.
            matching_engine: Optional matching engine override.
        """

        self.fee_bps = fee_bps
        self.maker_fee_bps = maker_fee_bps if maker_fee_bps is not None else fee_bps
        self.slippage_bps = slippage_bps
        self.slippage_volatility_multiplier = slippage_volatility_multiplier
        self.slippage_liquidity_multiplier = slippage_liquidity_multiplier
        self.max_market_spread_bps = max_market_spread_bps
        self.min_market_depth_1pct_usd = min_market_depth_1pct_usd
        self._matching_engine = matching_engine or MatchingEngine(
            fee_engine=FeeEngine(fee_bps),
            maker_fee_engine=FeeEngine(self.maker_fee_bps),
            slippage_engine=SlippageEngine(
                slippage_bps=slippage_bps,
                volatility_multiplier=slippage_volatility_multiplier,
                liquidity_multiplier=slippage_liquidity_multiplier,
            ),
            max_market_spread_bps=max_market_spread_bps,
            min_market_depth_1pct_usd=min_market_depth_1pct_usd,
        )

    def submit_market_order(
        self,
        order_request: OrderRequest,
        reference_price: Decimal,
        slippage_context: SlippageContext | None = None,
    ) -> tuple[SimOrder, Fill | None]:
        """Fill an internal market order request at a simulated price.

        Args:
            order_request: Internal order request generated by the portfolio layer.
            reference_price: Current market reference price.
            slippage_context: Optional market context for effective slippage.

        Returns:
            Simulated order and optional fill records.
        """

        return self._matching_engine.match_market_order(
            order_request, reference_price, slippage_context
        )

    def submit_limit_order(
        self,
        order_request: OrderRequest,
        reference_price: Decimal,
        available_quantity: Decimal | None = None,
        time_in_force: TimeInForce = "gtc",
    ) -> tuple[SimOrder, Fill | None]:
        """Submit an internal limit order request to simulated matching.

        Args:
            order_request: Internal limit order request generated by the
                portfolio layer.
            reference_price: Current market reference price.
            available_quantity: Optional simulated depth available to fill.
            time_in_force: Limit order expiry behavior.

        Returns:
            Simulated order and optional fill.
        """

        return self._matching_engine.match_limit_order(
            order_request, reference_price, available_quantity, time_in_force
        )
